  INFO root [2018-06-29 18:45:21,872] - 
  INFO root [2018-06-29 18:45:21,873] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 18:45:21,876] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 18:45:21,877] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 18:45:21,878] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 18:45:21,920] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 18:45:21,921] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 18:45:21,931] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12187 )
  INFO root [2018-06-29 18:45:21,931] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12187, SOMAXCONN=128.
  INFO root [2018-06-29 18:45:21,931] - server-configs:
  INFO root [2018-06-29 18:45:21,932] - 	internalAddr : 192.168.31.56:12187
  INFO root [2018-06-29 18:45:21,932] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 18:45:21,932] - 	componentID : 9000
  INFO root [2018-06-29 18:45:22,857] - Components::findLogger: found logger, addr:192.168.31.56:12184
  INFO root [2018-06-29 18:45:22,858] - Components::addComponent: reset orderLog, uid=29544!
  INFO root [2018-06-29 18:45:22,859] - Components::addComponent[logger], uid=29544, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 18:45:22,870] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 29544. PID: 5304 ----
  INFO root [2018-06-29 18:45:22,870] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 18:45:22,871] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 18:45:22,872] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 18:45:23,027] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 18:45:23,028] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 18:45:23,030] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 18:45:23,036] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 18:45:23,036] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 18:45:23,037] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 18:45:23,038] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 18:45:23,122] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 18:45:23,206] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 18:45:23,207] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 18:45:23,212] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 18:45:23,213] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 18:45:24,713] - ---- loginapp is running ----
 DEBUG root [2018-06-29 18:45:24,714] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 18:45:30,845] - Forwarding logs to logger[192.168.31.56:12184/0/0/0]...
 ERROR root [2018-06-29 18:47:08,954] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 18:47:08,958] - The following logs sent to logger failed:
  WARN root [2018-06-29 18:47:08,958] - ==> [2018-06-29 18:47:08 954] TCPPacketReceiver::processPendingEvents(192.168.31.56:12184): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 18:47:08,959] - ==> [2018-06-29 18:47:08 955] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 18:47:13,670] - 
  INFO root [2018-06-29 18:47:13,674] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 18:47:13,676] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 18:47:13,676] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 18:47:13,677] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 18:47:13,691] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 18:47:13,691] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 18:47:13,701] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12242 )
  INFO root [2018-06-29 18:47:13,702] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12242, SOMAXCONN=128.
  INFO root [2018-06-29 18:47:13,703] - server-configs:
  INFO root [2018-06-29 18:47:13,703] - 	internalAddr : 192.168.31.56:12242
  INFO root [2018-06-29 18:47:13,703] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 18:47:13,704] - 	componentID : 9000
  INFO root [2018-06-29 18:47:14,512] - Components::findLogger: found logger, addr:192.168.31.56:12241
  INFO root [2018-06-29 18:47:14,513] - Components::addComponent: reset orderLog, uid=29909!
  INFO root [2018-06-29 18:47:14,513] - Components::addComponent[logger], uid=29909, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 18:47:14,525] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 29909. PID: 3300 ----
  INFO root [2018-06-29 18:47:14,526] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 18:47:14,527] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 18:47:14,528] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 18:47:14,704] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 18:47:14,705] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 18:47:14,706] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 18:47:14,714] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 18:47:14,715] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 18:47:14,715] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 18:47:14,717] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 18:47:14,786] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 18:47:14,878] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 18:47:14,878] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 18:47:14,885] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 18:47:14,886] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 18:47:16,272] - ---- loginapp is running ----
 DEBUG root [2018-06-29 18:47:16,273] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 18:47:22,499] - Forwarding logs to logger[192.168.31.56:12241/0/0/0]...
 ERROR root [2018-06-29 18:49:44,489] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 18:49:44,497] - The following logs sent to logger failed:
  WARN root [2018-06-29 18:49:44,498] - ==> [2018-06-29 18:49:44 486] TCPPacketReceiver::processPendingEvents(192.168.31.56:12241): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 18:49:44,499] - ==> [2018-06-29 18:49:44 489] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 18:49:44,622] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12238): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 18:49:44,625] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 18:49:44,630] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 18:49:44,634] - onLoginAppShutDown()
  INFO root [2018-06-29 18:49:44,634] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 18:49:44,634] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 18:49:44,635] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 18:49:44,635] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 18:49:44,635] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 18:49:44,635] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 18:49:44,636] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 18:49:44,636] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 18:49:44,636] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 18:49:44,636] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 18:49:44,652] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 18:49:44,653] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 18:49:44,953] - ThreadPool::destroy(): waiting for thread(2)[0x7a2178,0x7a2110,], try=1
  INFO root [2018-06-29 18:49:50,092] - 
  INFO root [2018-06-29 18:49:50,093] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 18:49:50,094] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 18:49:50,095] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 18:49:50,095] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 18:49:50,105] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 18:49:50,106] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 18:49:50,110] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12327 )
  INFO root [2018-06-29 18:49:50,110] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12327, SOMAXCONN=128.
  INFO root [2018-06-29 18:49:50,110] - server-configs:
  INFO root [2018-06-29 18:49:50,111] - 	internalAddr : 192.168.31.56:12327
  INFO root [2018-06-29 18:49:50,111] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 18:49:50,111] - 	componentID : 9000
  INFO root [2018-06-29 18:49:52,130] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30422. PID: 10376 ----
  INFO root [2018-06-29 18:49:52,131] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 18:49:52,132] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 18:49:52,133] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 18:49:52,314] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 18:49:52,315] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 18:49:52,316] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 18:49:52,323] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 18:49:52,324] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 18:49:52,324] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 18:49:52,326] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 18:49:52,410] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 18:49:52,494] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 18:49:52,494] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 18:49:52,499] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 18:49:52,500] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 18:49:53,745] - ---- loginapp is running ----
 DEBUG root [2018-06-29 18:49:53,747] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 18:50:00,920] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 18:50:00,961] - Components::findComponents: found logger, addr:192.168.31.56:12329
  INFO root [2018-06-29 18:50:00,961] - Components::addComponent: reset orderLog, uid=30422!
  INFO root [2018-06-29 18:50:00,961] - Components::addComponent[logger], uid=30422, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 18:50:00,964] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 18:50:01,068] - Components::findComponents: found dbmgr, addr:192.168.31.56:12333
  INFO root [2018-06-29 18:50:01,068] - Components::addComponent: reset orderLog, uid=30422!
  INFO root [2018-06-29 18:50:01,069] - Components::addComponent[dbmgr], uid=30422, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 18:50:01,069] - Components::findComponents: found dbmgr, addr:192.168.31.56:12333
  WARN root [2018-06-29 18:50:02,069] - Forwarding logs to logger[192.168.31.56:12329/0/0/0]...
 ERROR root [2018-06-29 18:50:11,287] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 18:50:11,290] - The following logs sent to logger failed:
  INFO root [2018-06-29 18:50:11,291] - ==> [2018-06-29 18:50:10 080] Loginapp::onDbmgrInitCompleted:startGlobalOrder=2, startGroupOrder=1, digest=D83ADB1A7AC1302E807E36F0AD174A02.
  INFO root [2018-06-29 18:50:11,291] - ==> [2018-06-29 18:50:11 287] HTTPCBHandler::bind: 192.168.31.56:21103
  WARN root [2018-06-29 18:50:11,291] - ==> [2018-06-29 18:50:11 287] c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\lib\network\event_dispatcher.cpp:171: Profile callSystemTimers took 1.21 seconds
  WARN root [2018-06-29 18:50:11,291] - ==> [2018-06-29 18:50:11 287] TCPPacketReceiver::processPendingEvents(192.168.31.56:12329): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 18:50:11,292] - ==> [2018-06-29 18:50:11 288] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 18:50:11,292] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12333): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 18:50:11,293] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 18:50:11,295] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 18:50:11,296] - onLoginAppShutDown()
  INFO root [2018-06-29 18:50:11,296] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 18:50:11,296] - Shutdowner::onShutdownEnd: shutting down
  WARN root [2018-06-29 18:50:11,297] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12330): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [2018-06-29 18:50:11,297] - Components::removeComponentByChannel: baseappmgr : 5000, Normal exit!
 DEBUG root [2018-06-29 18:50:11,297] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 18:50:11,297] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 18:50:11,298] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 18:50:11,298] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 18:50:11,298] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 18:50:11,298] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 18:50:11,298] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 18:50:11,298] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 18:50:11,314] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 18:50:11,314] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-29 18:50:16,320] - 
  INFO root [2018-06-29 18:50:16,323] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 18:50:16,325] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 18:50:16,325] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 18:50:16,326] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 18:50:16,336] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 18:50:16,337] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 18:50:16,342] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12364 )
  INFO root [2018-06-29 18:50:16,342] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12364, SOMAXCONN=128.
  INFO root [2018-06-29 18:50:16,342] - server-configs:
  INFO root [2018-06-29 18:50:16,343] - 	internalAddr : 192.168.31.56:12364
  INFO root [2018-06-29 18:50:16,343] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 18:50:16,343] - 	componentID : 9000
  INFO root [2018-06-29 18:50:18,520] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30507. PID: 10488 ----
  INFO root [2018-06-29 18:50:18,522] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 18:50:18,522] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 18:50:18,523] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 18:50:18,724] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 18:50:18,726] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 18:50:18,727] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 18:50:18,734] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 18:50:18,735] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 18:50:18,735] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 18:50:18,738] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 18:50:18,877] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 18:50:18,973] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 18:50:18,973] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 18:50:18,979] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 18:50:18,981] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 18:50:19,909] - ---- loginapp is running ----
 DEBUG root [2018-06-29 18:50:19,910] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 18:50:27,039] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 18:50:27,047] - Components::findComponents: found logger, addr:192.168.31.56:12367
  INFO root [2018-06-29 18:50:27,047] - Components::addComponent: reset orderLog, uid=30507!
  INFO root [2018-06-29 18:50:27,047] - Components::addComponent[logger], uid=30507, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 18:50:27,051] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 18:50:27,054] - Components::findComponents: found logger, addr:192.168.31.56:12367
  INFO root [2018-06-29 18:50:27,157] - Components::findComponents: found dbmgr, addr:192.168.31.56:12369
  INFO root [2018-06-29 18:50:27,157] - Components::addComponent: reset orderLog, uid=30507!
  INFO root [2018-06-29 18:50:27,157] - Components::addComponent[dbmgr], uid=30507, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 18:50:27,159] - Components::findComponents: found dbmgr, addr:192.168.31.56:12369
  WARN root [2018-06-29 18:50:28,159] - Forwarding logs to logger[192.168.31.56:12367/0/0/0]...
 ERROR root [2018-06-29 19:08:25,015] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:08:25,026] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:08:25,027] - ==> [2018-06-29 19:08:25 009] TCPPacketReceiver::processPendingEvents(192.168.31.56:12367): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:08:25,027] - ==> [2018-06-29 19:08:25 016] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:08:25,133] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12369): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:08:25,137] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:08:25,147] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:08:25,168] - onLoginAppShutDown()
  INFO root [2018-06-29 19:08:25,168] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:08:25,169] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:08:25,170] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:08:25,170] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:08:25,170] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:08:25,171] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:08:25,171] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:08:25,171] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:08:25,172] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:08:25,172] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:08:25,190] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:08:25,190] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:08:25,491] - ThreadPool::destroy(): waiting for thread(2)[0x4f11a0,0x4f1138,], try=1
  INFO root [2018-06-29 19:08:32,546] - 
  INFO root [2018-06-29 19:08:32,547] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:08:32,550] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:08:32,550] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:08:32,551] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:08:32,567] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:08:32,567] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:08:32,572] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12762 )
  INFO root [2018-06-29 19:08:32,573] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12762, SOMAXCONN=128.
  INFO root [2018-06-29 19:08:32,573] - server-configs:
  INFO root [2018-06-29 19:08:32,573] - 	internalAddr : 192.168.31.56:12762
  INFO root [2018-06-29 19:08:32,574] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:08:32,574] - 	componentID : 9000
  INFO root [2018-06-29 19:08:33,860] - Components::findLogger: found logger, addr:192.168.31.56:12755
  INFO root [2018-06-29 19:08:33,861] - Components::addComponent: reset orderLog, uid=1318!
  INFO root [2018-06-29 19:08:33,862] - Components::addComponent[logger], uid=1318, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:08:33,875] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1318. PID: 3164 ----
  INFO root [2018-06-29 19:08:33,876] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:08:33,878] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:08:33,879] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:08:34,106] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:08:34,108] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:08:34,109] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:08:34,117] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:08:34,118] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:08:34,119] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:08:34,120] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:08:34,220] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:08:34,316] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:08:34,317] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:08:34,323] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:08:34,324] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:08:35,854] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:08:35,856] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 19:08:42,071] - Forwarding logs to logger[192.168.31.56:12755/0/0/0]...
 ERROR root [2018-06-29 19:12:16,441] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:12:16,465] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:12:16,465] - ==> [2018-06-29 19:12:16 431] TCPPacketReceiver::processPendingEvents(192.168.31.56:12755): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:12:16,466] - ==> [2018-06-29 19:12:16 442] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:12:16,572] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12759): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:12:16,580] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:12:16,596] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:12:16,601] - onLoginAppShutDown()
  INFO root [2018-06-29 19:12:16,601] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:12:16,601] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:12:16,602] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:12:16,602] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:12:16,603] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:12:16,603] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:12:16,603] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:12:16,604] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:12:16,604] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:12:16,604] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:12:16,623] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:12:16,624] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:12:16,924] - ThreadPool::destroy(): waiting for thread(2)[0x682170,0x682108,], try=1
  INFO root [2018-06-29 19:12:24,717] - 
  INFO root [2018-06-29 19:12:24,779] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:12:24,781] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:12:24,782] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:12:24,783] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:12:24,809] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:12:24,809] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:12:24,851] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12846 )
  INFO root [2018-06-29 19:12:24,851] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12846, SOMAXCONN=128.
  INFO root [2018-06-29 19:12:24,852] - server-configs:
  INFO root [2018-06-29 19:12:24,852] - 	internalAddr : 192.168.31.56:12846
  INFO root [2018-06-29 19:12:24,852] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:12:24,852] - 	componentID : 9000
  INFO root [2018-06-29 19:12:27,058] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2076. PID: 10144 ----
  INFO root [2018-06-29 19:12:27,060] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:12:27,060] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:12:27,061] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:12:27,350] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:12:27,353] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:12:27,355] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:12:27,363] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:12:27,364] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:12:27,365] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:12:27,367] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:12:27,578] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:12:27,696] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:12:27,697] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:12:27,705] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:12:27,707] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:12:29,147] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:12:29,149] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 19:12:36,305] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 19:12:36,350] - Components::findComponents: found logger, addr:192.168.31.56:12848
  INFO root [2018-06-29 19:12:36,350] - Components::addComponent: reset orderLog, uid=2076!
  INFO root [2018-06-29 19:12:36,351] - Components::addComponent[logger], uid=2076, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:12:36,353] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 19:12:36,454] - Components::findComponents: found dbmgr, addr:192.168.31.56:12845
  INFO root [2018-06-29 19:12:36,454] - Components::addComponent: reset orderLog, uid=2076!
  INFO root [2018-06-29 19:12:36,454] - Components::addComponent[dbmgr], uid=2076, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:12:36,455] - Components::findComponents: found dbmgr, addr:192.168.31.56:12845
  WARN root [2018-06-29 19:12:37,455] - Forwarding logs to logger[192.168.31.56:12848/0/0/0]...
 ERROR root [2018-06-29 19:12:46,136] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:12:46,140] - The following logs sent to logger failed:
  INFO root [2018-06-29 19:12:46,141] - ==> [2018-06-29 19:12:44 926] Loginapp::onDbmgrInitCompleted:startGlobalOrder=3, startGroupOrder=1, digest=D83ADB1A7AC1302E807E36F0AD174A02.
  INFO root [2018-06-29 19:12:46,141] - ==> [2018-06-29 19:12:46 134] HTTPCBHandler::bind: 192.168.31.56:21103
  WARN root [2018-06-29 19:12:46,142] - ==> [2018-06-29 19:12:46 134] c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\lib\network\event_dispatcher.cpp:171: Profile callSystemTimers took 1.21 seconds
  WARN root [2018-06-29 19:12:46,143] - ==> [2018-06-29 19:12:46 136] TCPPacketReceiver::processPendingEvents(192.168.31.56:12848): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:12:46,143] - ==> [2018-06-29 19:12:46 137] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:12:46,144] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12845): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:12:46,145] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:12:46,149] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:12:46,152] - onLoginAppShutDown()
  INFO root [2018-06-29 19:12:46,152] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:12:46,152] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:12:46,153] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:12:46,153] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:12:46,153] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:12:46,154] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:12:46,154] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:12:46,154] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:12:46,155] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:12:46,155] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:12:46,176] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:12:46,176] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:12:46,477] - ThreadPool::destroy(): waiting for thread(2)[0x552170,0x552108,], try=1
  INFO root [2018-06-29 19:14:31,528] - 
  INFO root [2018-06-29 19:14:31,529] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:14:31,531] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:14:31,532] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:14:31,532] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:14:31,549] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:14:31,550] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:14:31,563] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12914 )
  INFO root [2018-06-29 19:14:31,563] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12914, SOMAXCONN=128.
  INFO root [2018-06-29 19:14:31,564] - server-configs:
  INFO root [2018-06-29 19:14:31,564] - 	internalAddr : 192.168.31.56:12914
  INFO root [2018-06-29 19:14:31,564] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:14:31,564] - 	componentID : 9000
  INFO root [2018-06-29 19:14:33,862] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2490. PID: 9952 ----
  INFO root [2018-06-29 19:14:33,864] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:14:33,865] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:14:33,865] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:14:34,086] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:14:34,088] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:14:34,089] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:14:34,099] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:14:34,100] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:14:34,101] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:14:34,102] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:14:34,356] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:14:34,546] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:14:34,546] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:14:34,555] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:14:34,557] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:14:35,800] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:14:35,803] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 19:14:42,955] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 19:14:42,974] - Components::findComponents: found logger, addr:192.168.31.56:12919
  INFO root [2018-06-29 19:14:42,974] - Components::addComponent: reset orderLog, uid=2490!
  INFO root [2018-06-29 19:14:42,974] - Components::addComponent[logger], uid=2490, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:14:42,976] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 19:14:43,080] - Components::findComponents: found dbmgr, addr:192.168.31.56:12915
  INFO root [2018-06-29 19:14:43,081] - Components::addComponent: reset orderLog, uid=2490!
  INFO root [2018-06-29 19:14:43,081] - Components::addComponent[dbmgr], uid=2490, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:14:43,081] - Components::findComponents: found dbmgr, addr:192.168.31.56:12915
  WARN root [2018-06-29 19:14:44,081] - Forwarding logs to logger[192.168.31.56:12919/0/0/0]...
 ERROR root [2018-06-29 19:14:57,015] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:14:57,031] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:14:57,031] - ==> [2018-06-29 19:14:57 011] TCPPacketReceiver::processPendingEvents(192.168.31.56:12919): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:14:57,032] - ==> [2018-06-29 19:14:57 016] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:14:57,133] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12915): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:14:57,141] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:14:57,144] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:14:57,145] - onLoginAppShutDown()
  INFO root [2018-06-29 19:14:57,145] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:14:57,145] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:14:57,146] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:14:57,146] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:14:57,147] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:14:57,147] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:14:57,147] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:14:57,148] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:14:57,148] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:14:57,149] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:14:57,166] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:14:57,166] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:14:57,466] - ThreadPool::destroy(): waiting for thread(2)[0x712170,0x712108,], try=1
  INFO root [2018-06-29 19:15:27,846] - 
  INFO root [2018-06-29 19:15:27,887] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:15:27,890] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:15:27,890] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:15:27,893] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:15:27,920] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:15:27,921] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:15:27,940] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12960 )
  INFO root [2018-06-29 19:15:27,941] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12960, SOMAXCONN=128.
  INFO root [2018-06-29 19:15:27,941] - server-configs:
  INFO root [2018-06-29 19:15:27,941] - 	internalAddr : 192.168.31.56:12960
  INFO root [2018-06-29 19:15:27,942] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:15:27,942] - 	componentID : 9000
  INFO root [2018-06-29 19:15:30,009] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2673. PID: 2912 ----
  INFO root [2018-06-29 19:15:30,011] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:15:30,012] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:15:30,012] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:15:30,197] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:15:30,198] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:15:30,199] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:15:30,207] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:15:30,210] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:15:30,210] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:15:30,212] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:15:30,318] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:15:30,429] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:15:30,429] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:15:30,434] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:15:30,438] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:15:31,399] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:15:31,400] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 19:15:38,535] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 19:15:38,564] - Components::findComponents: found logger, addr:192.168.31.56:12965
  INFO root [2018-06-29 19:15:38,564] - Components::addComponent: reset orderLog, uid=2673!
  INFO root [2018-06-29 19:15:38,565] - Components::addComponent[logger], uid=2673, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:15:38,567] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 19:15:38,671] - Components::findComponents: found dbmgr, addr:192.168.31.56:12958
  INFO root [2018-06-29 19:15:38,671] - Components::addComponent: reset orderLog, uid=2673!
  INFO root [2018-06-29 19:15:38,672] - Components::addComponent[dbmgr], uid=2673, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:15:38,672] - Components::findComponents: found dbmgr, addr:192.168.31.56:12958
  WARN root [2018-06-29 19:15:39,672] - Forwarding logs to logger[192.168.31.56:12965/0/0/0]...
 ERROR root [2018-06-29 19:17:09,001] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:17:09,028] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:17:09,029] - ==> [2018-06-29 19:17:08 998] TCPPacketReceiver::processPendingEvents(192.168.31.56:12965): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:17:09,030] - ==> [2018-06-29 19:17:09 002] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:17:09,169] - TCPPacketReceiver::processPendingEvents(192.168.31.56:12958): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:17:09,176] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:17:09,194] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:17:09,199] - onLoginAppShutDown()
  INFO root [2018-06-29 19:17:09,200] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:17:09,201] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:17:09,202] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:17:09,202] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:17:09,203] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:17:09,203] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:17:09,204] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:17:09,204] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:17:09,204] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:17:09,205] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:17:09,226] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:17:09,227] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:17:09,527] - ThreadPool::destroy(): waiting for thread(2)[0x822170,0x822108,], try=1
  INFO root [2018-06-29 19:17:14,558] - 
  INFO root [2018-06-29 19:17:14,565] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:17:14,567] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:17:14,568] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:17:14,569] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:17:14,604] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:17:14,604] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:17:14,608] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13028 )
  INFO root [2018-06-29 19:17:14,609] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13028, SOMAXCONN=128.
  INFO root [2018-06-29 19:17:14,609] - server-configs:
  INFO root [2018-06-29 19:17:14,609] - 	internalAddr : 192.168.31.56:13028
  INFO root [2018-06-29 19:17:14,610] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:17:14,610] - 	componentID : 9000
  INFO root [2018-06-29 19:17:16,753] - Components::findLogger: found logger, addr:192.168.31.56:13027
  INFO root [2018-06-29 19:17:16,754] - Components::addComponent: reset orderLog, uid=3023!
  INFO root [2018-06-29 19:17:16,755] - Components::addComponent[logger], uid=3023, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:17:16,770] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3023. PID: 10348 ----
  INFO root [2018-06-29 19:17:16,771] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:17:16,774] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:17:16,774] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:17:16,987] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:17:16,988] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:17:16,989] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:17:16,997] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:17:16,998] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:17:16,998] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:17:17,000] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:17:17,322] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:17:17,518] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:17:17,519] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:17:17,524] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:17:17,525] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:17:18,920] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:17:18,921] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 19:17:25,072] - Forwarding logs to logger[192.168.31.56:13027/0/0/0]...
 ERROR root [2018-06-29 19:17:42,737] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:17:42,791] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:17:42,792] - ==> [2018-06-29 19:17:42 735] TCPPacketReceiver::processPendingEvents(192.168.31.56:13027): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:17:42,793] - ==> [2018-06-29 19:17:42 738] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:17:42,877] - TCPPacketReceiver::processPendingEvents(192.168.31.56:13030): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:17:42,888] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:17:42,926] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:17:42,927] - onLoginAppShutDown()
  INFO root [2018-06-29 19:17:42,927] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:17:42,927] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:17:42,928] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:17:42,928] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:17:42,929] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:17:42,929] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:17:42,929] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:17:42,929] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:17:42,930] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:17:42,930] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:17:42,951] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:17:42,951] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:17:43,252] - ThreadPool::destroy(): waiting for thread(2)[0x332170,0x332108,], try=1
  INFO root [2018-06-29 19:17:48,349] - 
  INFO root [2018-06-29 19:17:48,351] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:17:48,353] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:17:48,353] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:17:48,354] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:17:48,412] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:17:48,412] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:17:48,438] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13070 )
  INFO root [2018-06-29 19:17:48,438] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13070, SOMAXCONN=128.
  INFO root [2018-06-29 19:17:48,439] - server-configs:
  INFO root [2018-06-29 19:17:48,439] - 	internalAddr : 192.168.31.56:13070
  INFO root [2018-06-29 19:17:48,439] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:17:48,439] - 	componentID : 9000
  INFO root [2018-06-29 19:17:49,455] - Components::findLogger: found logger, addr:192.168.31.56:13063
  INFO root [2018-06-29 19:17:49,456] - Components::addComponent: reset orderLog, uid=3134!
  INFO root [2018-06-29 19:17:49,456] - Components::addComponent[logger], uid=3134, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:17:49,466] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3134. PID: 7324 ----
  INFO root [2018-06-29 19:17:49,467] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:17:49,467] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:17:49,468] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:17:49,651] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:17:49,652] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:17:49,653] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:17:49,661] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:17:49,662] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:17:49,662] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:17:49,664] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:17:49,729] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:17:49,799] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:17:49,799] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:17:49,803] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:17:49,805] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:17:51,811] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:17:51,812] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 19:17:57,965] - Forwarding logs to logger[192.168.31.56:13063/0/0/0]...
 ERROR root [2018-06-29 19:20:01,341] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:20:01,349] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:20:01,350] - ==> [2018-06-29 19:20:01 339] TCPPacketReceiver::processPendingEvents(192.168.31.56:13063): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:20:01,350] - ==> [2018-06-29 19:20:01 342] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:20:01,474] - TCPPacketReceiver::processPendingEvents(192.168.31.56:13069): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:20:01,477] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:20:01,485] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:20:01,495] - onLoginAppShutDown()
  INFO root [2018-06-29 19:20:01,495] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:20:01,495] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:20:01,496] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:20:01,496] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:20:01,496] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:20:01,497] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:20:01,497] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:20:01,497] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:20:01,497] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:20:01,498] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:20:01,516] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:20:01,517] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:20:01,817] - ThreadPool::destroy(): waiting for thread(2)[0x19811a0,0x1981138,], try=1
  INFO root [2018-06-29 19:22:40,144] - 
  INFO root [2018-06-29 19:22:40,145] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:22:40,146] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:22:40,146] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:22:40,146] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:22:40,156] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:22:40,156] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:22:40,160] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13168 )
  INFO root [2018-06-29 19:22:40,160] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13168, SOMAXCONN=128.
  INFO root [2018-06-29 19:22:40,160] - server-configs:
  INFO root [2018-06-29 19:22:40,160] - 	internalAddr : 192.168.31.56:13168
  INFO root [2018-06-29 19:22:40,160] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:22:40,160] - 	componentID : 9000
  INFO root [2018-06-29 19:22:42,279] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4087. PID: 496 ----
  INFO root [2018-06-29 19:22:42,281] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:22:42,282] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:22:42,282] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:22:42,557] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:22:42,558] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:22:42,560] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:22:42,567] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:22:42,568] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:22:42,569] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:22:42,570] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:22:42,893] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:22:43,280] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:22:43,282] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:22:43,287] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:22:43,289] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:22:45,028] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:22:45,029] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 19:22:52,167] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 19:22:52,201] - Components::findComponents: found logger, addr:192.168.31.56:13175
  INFO root [2018-06-29 19:22:52,201] - Components::addComponent: reset orderLog, uid=4087!
  INFO root [2018-06-29 19:22:52,201] - Components::addComponent[logger], uid=4087, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:22:52,204] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 19:22:52,305] - Components::findComponents: found dbmgr, addr:192.168.31.56:13176
  INFO root [2018-06-29 19:22:52,305] - Components::addComponent: reset orderLog, uid=4087!
  INFO root [2018-06-29 19:22:52,305] - Components::addComponent[dbmgr], uid=4087, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:22:52,311] - Components::findComponents: found dbmgr, addr:192.168.31.56:13176
  WARN root [2018-06-29 19:22:53,311] - Forwarding logs to logger[192.168.31.56:13175/0/0/0]...
 ERROR root [2018-06-29 19:25:36,464] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:25:36,473] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:25:36,474] - ==> [2018-06-29 19:25:36 463] TCPPacketReceiver::processPendingEvents(192.168.31.56:13175): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:25:36,474] - ==> [2018-06-29 19:25:36 465] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:25:36,586] - TCPPacketReceiver::processPendingEvents(192.168.31.56:13176): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:25:36,587] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:25:36,598] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:25:36,604] - onLoginAppShutDown()
  INFO root [2018-06-29 19:25:36,604] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:25:36,604] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:25:36,605] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:25:36,605] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:25:36,606] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:25:36,606] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:25:36,606] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:25:36,606] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:25:36,607] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:25:36,607] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:25:36,625] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:25:36,625] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:25:36,925] - ThreadPool::destroy(): waiting for thread(2)[0x4411a0,0x441138,], try=1
  INFO root [2018-06-29 19:25:47,900] - 
  INFO root [2018-06-29 19:25:47,910] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:25:47,912] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:25:47,913] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:25:47,914] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:25:47,948] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:25:47,949] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:25:47,963] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13260 )
  INFO root [2018-06-29 19:25:47,964] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13260, SOMAXCONN=128.
  INFO root [2018-06-29 19:25:47,964] - server-configs:
  INFO root [2018-06-29 19:25:47,964] - 	internalAddr : 192.168.31.56:13260
  INFO root [2018-06-29 19:25:47,965] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:25:47,965] - 	componentID : 9000
  INFO root [2018-06-29 19:25:49,144] - Components::findLogger: found logger, addr:192.168.31.56:13255
  INFO root [2018-06-29 19:25:49,145] - Components::addComponent: reset orderLog, uid=4698!
  INFO root [2018-06-29 19:25:49,145] - Components::addComponent[logger], uid=4698, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:25:49,158] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4698. PID: 4380 ----
  INFO root [2018-06-29 19:25:49,158] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:25:49,159] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:25:49,160] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:25:49,322] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:25:49,323] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:25:49,324] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:25:49,329] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:25:49,330] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:25:49,331] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:25:49,332] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:25:49,414] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:25:49,507] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:25:49,508] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:25:49,513] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:25:49,514] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:25:51,739] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:25:51,740] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 19:25:57,849] - Forwarding logs to logger[192.168.31.56:13255/0/0/0]...
 ERROR root [2018-06-29 19:31:20,777] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:31:20,804] - The following logs sent to logger failed:
  WARN root [2018-06-29 19:31:20,804] - ==> [2018-06-29 19:31:20 774] TCPPacketReceiver::processPendingEvents(192.168.31.56:13255): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:31:20,805] - ==> [2018-06-29 19:31:20 779] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 19:31:20,909] - TCPPacketReceiver::processPendingEvents(192.168.31.56:13261): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 19:31:20,921] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 19:31:20,929] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 19:31:20,929] - onLoginAppShutDown()
  INFO root [2018-06-29 19:31:20,930] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 19:31:20,930] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 19:31:20,931] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:31:20,931] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:31:20,931] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:31:20,932] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:31:20,932] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:31:20,932] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:31:20,932] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:31:20,933] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:31:20,952] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 19:31:20,953] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 19:31:21,253] - ThreadPool::destroy(): waiting for thread(2)[0x782170,0x782108,], try=1
  INFO root [2018-06-29 19:36:57,413] - 
  INFO root [2018-06-29 19:36:57,423] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 19:36:57,425] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 19:36:57,428] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 19:36:57,428] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 19:36:57,454] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 19:36:57,455] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 19:36:57,461] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13469 )
  INFO root [2018-06-29 19:36:57,462] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13469, SOMAXCONN=128.
  INFO root [2018-06-29 19:36:57,462] - server-configs:
  INFO root [2018-06-29 19:36:57,463] - 	internalAddr : 192.168.31.56:13469
  INFO root [2018-06-29 19:36:57,463] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 19:36:57,463] - 	componentID : 9000
  INFO root [2018-06-29 19:36:58,798] - Components::findLogger: found logger, addr:192.168.31.56:13468
  INFO root [2018-06-29 19:36:58,799] - Components::addComponent: reset orderLog, uid=6886!
  INFO root [2018-06-29 19:36:58,800] - Components::addComponent[logger], uid=6886, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 19:36:58,812] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 6886. PID: 9360 ----
  INFO root [2018-06-29 19:36:58,814] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 19:36:58,814] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 19:36:58,815] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 19:36:58,979] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 19:36:58,980] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 19:36:58,981] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 19:36:58,992] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 19:36:58,993] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 19:36:58,994] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 19:36:58,996] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 19:36:59,095] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 19:36:59,194] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 19:36:59,194] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 19:36:59,198] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 19:36:59,200] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 19:37:01,760] - ---- loginapp is running ----
 DEBUG root [2018-06-29 19:37:01,760] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 19:37:07,896] - Forwarding logs to logger[192.168.31.56:13468/0/0/0]...
 ERROR root [2018-06-29 20:13:21,451] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:13:21,469] - The following logs sent to logger failed:
  WARN root [2018-06-29 20:13:21,470] - ==> [2018-06-29 20:13:21 447] TCPPacketReceiver::processPendingEvents(192.168.31.56:13468): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:13:21,470] - ==> [2018-06-29 20:13:21 453] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 20:13:21,581] - TCPPacketReceiver::processPendingEvents(192.168.31.56:13473): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:13:21,582] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:13:21,584] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 20:13:21,585] - onLoginAppShutDown()
  INFO root [2018-06-29 20:13:21,585] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 20:13:21,585] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 20:13:21,586] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:13:21,586] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:13:21,586] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:13:21,587] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:13:21,587] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:13:21,587] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:13:21,588] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:13:21,588] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:13:21,606] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 20:13:21,606] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 20:13:21,906] - ThreadPool::destroy(): waiting for thread(2)[0x6711a0,0x671138,], try=1
  INFO root [2018-06-29 20:13:25,821] - 
  INFO root [2018-06-29 20:13:25,822] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:13:25,824] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:13:25,824] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:13:25,824] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:13:25,833] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:13:25,834] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:13:25,837] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14060 )
  INFO root [2018-06-29 20:13:25,838] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14060, SOMAXCONN=128.
  INFO root [2018-06-29 20:13:25,838] - server-configs:
  INFO root [2018-06-29 20:13:25,838] - 	internalAddr : 192.168.31.56:14060
  INFO root [2018-06-29 20:13:25,838] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:13:25,838] - 	componentID : 9000
  INFO root [2018-06-29 20:13:27,774] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 14031. PID: 9584 ----
  INFO root [2018-06-29 20:13:27,775] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:13:27,776] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:13:27,777] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:13:27,932] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:13:27,933] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:13:27,934] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:13:27,938] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:13:27,939] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:13:27,939] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:13:27,940] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:13:28,017] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:13:28,094] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:13:28,094] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:13:28,100] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:13:28,101] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:13:30,025] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:13:30,026] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:13:37,180] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 20:13:37,231] - Components::findComponents: found logger, addr:192.168.31.56:14063
  INFO root [2018-06-29 20:13:37,231] - Components::addComponent: reset orderLog, uid=14031!
  INFO root [2018-06-29 20:13:37,232] - Components::addComponent[logger], uid=14031, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:13:37,235] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 20:13:37,335] - Components::findComponents: found dbmgr, addr:192.168.31.56:14066
  INFO root [2018-06-29 20:13:37,336] - Components::addComponent: reset orderLog, uid=14031!
  INFO root [2018-06-29 20:13:37,336] - Components::addComponent[dbmgr], uid=14031, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:13:37,337] - Components::findComponents: found dbmgr, addr:192.168.31.56:14066
  WARN root [2018-06-29 20:13:38,340] - Forwarding logs to logger[192.168.31.56:14063/0/0/0]...
 ERROR root [2018-06-29 20:18:18,149] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:18:18,183] - The following logs sent to logger failed:
  WARN root [2018-06-29 20:18:18,183] - ==> [2018-06-29 20:18:18 141] TCPPacketReceiver::processPendingEvents(192.168.31.56:14063): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:18:18,184] - ==> [2018-06-29 20:18:18 150] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 20:18:18,334] - TCPPacketReceiver::processPendingEvents(192.168.31.56:14066): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:18:18,340] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:18:18,345] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 20:18:18,346] - onLoginAppShutDown()
  INFO root [2018-06-29 20:18:18,346] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 20:18:18,346] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 20:18:18,347] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:18:18,347] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:18:18,348] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:18:18,348] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:18:18,348] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:18:18,349] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:18:18,349] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:18:18,350] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:18:18,374] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 20:18:18,375] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 20:18:18,675] - ThreadPool::destroy(): waiting for thread(2)[0x19e2178,0x19e2110,], try=1
  INFO root [2018-06-29 20:23:34,435] - 
  INFO root [2018-06-29 20:23:34,436] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:23:34,438] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:23:34,438] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:23:34,439] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:23:34,448] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:23:34,449] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:23:34,452] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14467 )
  INFO root [2018-06-29 20:23:34,452] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14467, SOMAXCONN=128.
  INFO root [2018-06-29 20:23:34,453] - server-configs:
  INFO root [2018-06-29 20:23:34,453] - 	internalAddr : 192.168.31.56:14467
  INFO root [2018-06-29 20:23:34,453] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:23:34,453] - 	componentID : 9000
  INFO root [2018-06-29 20:23:36,347] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 16020. PID: 2924 ----
  INFO root [2018-06-29 20:23:36,348] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:23:36,349] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:23:36,350] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:23:36,525] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:23:36,527] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:23:36,528] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:23:36,535] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:23:36,536] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:23:36,536] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:23:36,538] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:23:36,701] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:23:36,800] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:23:36,800] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:23:36,812] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:23:36,813] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:23:38,206] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:23:38,207] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:23:44,280] - 
  INFO root [2018-06-29 20:23:44,281] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:23:44,283] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:23:44,284] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:23:44,285] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:23:44,297] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:23:44,297] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:23:44,302] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14489 )
  INFO root [2018-06-29 20:23:44,302] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14489, SOMAXCONN=128.
  INFO root [2018-06-29 20:23:44,303] - server-configs:
  INFO root [2018-06-29 20:23:44,303] - 	internalAddr : 192.168.31.56:14489
  INFO root [2018-06-29 20:23:44,303] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:23:44,304] - 	componentID : 9000
  INFO root [2018-06-29 20:23:46,602] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 16052. PID: 6240 ----
  INFO root [2018-06-29 20:23:46,603] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:23:46,604] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:23:46,604] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:23:46,828] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:23:46,830] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:23:46,831] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:23:46,838] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:23:46,839] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:23:46,840] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:23:46,841] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:23:46,967] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:23:47,127] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:23:47,128] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:23:47,133] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:23:47,135] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:23:48,297] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:23:48,298] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:23:55,454] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 20:23:55,472] - Components::findComponents: found logger, addr:192.168.31.56:14488
  INFO root [2018-06-29 20:23:55,472] - Components::addComponent: reset orderLog, uid=16052!
  INFO root [2018-06-29 20:23:55,472] - Components::addComponent[logger], uid=16052, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:23:55,474] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 20:23:55,576] - Components::findComponents: found dbmgr, addr:192.168.31.56:14485
  INFO root [2018-06-29 20:23:55,576] - Components::addComponent: reset orderLog, uid=16052!
  INFO root [2018-06-29 20:23:55,576] - Components::addComponent[dbmgr], uid=16052, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:23:55,578] - Components::findComponents: found dbmgr, addr:192.168.31.56:14485
  WARN root [2018-06-29 20:23:56,579] - Forwarding logs to logger[192.168.31.56:14488/0/0/0]...
 ERROR root [2018-06-29 20:31:08,083] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:31:08,111] - The following logs sent to logger failed:
  WARN root [2018-06-29 20:31:08,112] - ==> [2018-06-29 20:31:08 083] TCPPacketReceiver::processPendingEvents(192.168.31.56:14488): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:31:08,112] - ==> [2018-06-29 20:31:08 084] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 20:31:08,255] - TCPPacketReceiver::processPendingEvents(192.168.31.56:14485): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:31:08,260] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:31:08,269] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 20:31:08,272] - onLoginAppShutDown()
  INFO root [2018-06-29 20:31:08,273] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 20:31:08,273] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 20:31:08,274] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:31:08,274] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:31:08,275] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:31:08,275] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:31:08,275] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:31:08,276] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:31:08,276] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:31:08,277] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:31:08,297] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 20:31:08,298] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 20:31:08,598] - ThreadPool::destroy(): waiting for thread(2)[0x4e11a0,0x4e1138,], try=1
  INFO root [2018-06-29 20:38:20,637] - 
  INFO root [2018-06-29 20:38:20,638] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:38:20,640] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:38:20,642] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:38:20,642] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:38:20,657] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:38:20,657] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:38:20,663] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14721 )
  INFO root [2018-06-29 20:38:20,664] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14721, SOMAXCONN=128.
  INFO root [2018-06-29 20:38:20,664] - server-configs:
  INFO root [2018-06-29 20:38:20,664] - 	internalAddr : 192.168.31.56:14721
  INFO root [2018-06-29 20:38:20,665] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:38:20,665] - 	componentID : 9000
  INFO root [2018-06-29 20:38:21,914] - Components::findLogger: found logger, addr:192.168.31.56:14718
  INFO root [2018-06-29 20:38:21,914] - Components::addComponent: reset orderLog, uid=18913!
  INFO root [2018-06-29 20:38:21,915] - Components::addComponent[logger], uid=18913, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:38:21,923] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 18913. PID: 1908 ----
  INFO root [2018-06-29 20:38:21,924] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:38:21,925] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:38:21,926] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:38:22,093] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:38:22,094] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:38:22,096] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:38:22,105] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:38:22,106] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:38:22,107] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:38:22,109] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:38:22,211] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:38:22,312] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:38:22,313] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:38:22,319] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:38:22,321] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:38:24,184] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:38:24,186] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 20:38:30,520] - Forwarding logs to logger[192.168.31.56:14718/0/0/0]...
 ERROR root [2018-06-29 20:44:22,389] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:44:22,391] - The following logs sent to logger failed:
  WARN root [2018-06-29 20:44:22,391] - ==> [2018-06-29 20:44:22 386] TCPPacketReceiver::processPendingEvents(192.168.31.56:14718): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:44:22,392] - ==> [2018-06-29 20:44:22 390] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 20:44:22,518] - TCPPacketReceiver::processPendingEvents(192.168.31.56:14719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:44:22,523] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:44:22,526] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 20:44:22,528] - onLoginAppShutDown()
  INFO root [2018-06-29 20:44:22,529] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 20:44:22,529] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 20:44:22,530] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:44:22,530] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:44:22,531] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:44:22,531] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:44:22,532] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:44:22,532] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:44:22,532] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:44:22,533] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:44:22,552] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 20:44:22,553] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 20:44:22,853] - ThreadPool::destroy(): waiting for thread(2)[0x3e11a0,0x3e1138,], try=1
  INFO root [2018-06-29 20:44:30,931] - 
  INFO root [2018-06-29 20:44:30,932] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:44:30,934] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:44:30,935] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:44:30,936] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:44:30,957] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:44:30,957] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:44:30,962] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14926 )
  INFO root [2018-06-29 20:44:30,962] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14926, SOMAXCONN=128.
  INFO root [2018-06-29 20:44:30,963] - server-configs:
  INFO root [2018-06-29 20:44:30,963] - 	internalAddr : 192.168.31.56:14926
  INFO root [2018-06-29 20:44:30,963] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:44:30,963] - 	componentID : 9000
  INFO root [2018-06-29 20:44:33,226] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 20121. PID: 6412 ----
  INFO root [2018-06-29 20:44:33,435] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:44:33,438] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:44:33,438] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:44:33,711] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:44:33,712] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:44:33,713] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:44:33,722] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:44:33,723] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:44:33,723] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:44:33,725] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:44:33,927] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:44:34,229] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:44:34,230] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:44:34,236] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:44:34,237] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:44:35,673] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:44:35,675] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:44:41,640] - 
  INFO root [2018-06-29 20:44:41,641] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:44:41,644] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:44:41,645] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:44:41,645] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:44:41,681] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:44:41,682] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:44:41,687] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14947 )
  INFO root [2018-06-29 20:44:41,688] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14947, SOMAXCONN=128.
  INFO root [2018-06-29 20:44:41,688] - server-configs:
  INFO root [2018-06-29 20:44:41,689] - 	internalAddr : 192.168.31.56:14947
  INFO root [2018-06-29 20:44:41,689] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:44:41,689] - 	componentID : 9000
  INFO root [2018-06-29 20:44:43,863] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 20157. PID: 10492 ----
  INFO root [2018-06-29 20:44:43,865] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:44:43,865] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:44:43,867] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:44:44,061] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:44:44,066] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:44:44,067] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:44:44,076] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:44:44,079] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:44:44,080] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:44:44,082] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:44:44,199] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:44:44,331] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:44:44,331] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:44:44,338] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:44:44,340] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:44:46,152] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:44:46,155] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:44:53,348] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 20:44:53,412] - Components::findComponents: found logger, addr:192.168.31.56:14942
  INFO root [2018-06-29 20:44:53,413] - Components::addComponent: reset orderLog, uid=20157!
  INFO root [2018-06-29 20:44:53,413] - Components::addComponent[logger], uid=20157, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:44:53,416] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 20:44:53,517] - Components::findComponents: found dbmgr, addr:192.168.31.56:14946
  INFO root [2018-06-29 20:44:53,517] - Components::addComponent: reset orderLog, uid=20157!
  INFO root [2018-06-29 20:44:53,518] - Components::addComponent[dbmgr], uid=20157, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:44:53,519] - Components::findComponents: found dbmgr, addr:192.168.31.56:14946
  WARN root [2018-06-29 20:44:54,519] - Forwarding logs to logger[192.168.31.56:14942/0/0/0]...
 ERROR root [2018-06-29 20:54:12,299] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:54:12,321] - The following logs sent to logger failed:
  WARN root [2018-06-29 20:54:12,321] - ==> [2018-06-29 20:54:12 295] TCPPacketReceiver::processPendingEvents(192.168.31.56:14942): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:54:12,322] - ==> [2018-06-29 20:54:12 299] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 20:54:12,442] - TCPPacketReceiver::processPendingEvents(192.168.31.56:14946): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:54:12,445] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:54:12,450] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 20:54:12,455] - onLoginAppShutDown()
  INFO root [2018-06-29 20:54:12,456] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 20:54:12,456] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 20:54:12,457] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:54:12,457] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:54:12,457] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:54:12,458] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:54:12,458] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:54:12,459] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:54:12,459] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:54:12,459] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:54:12,479] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 20:54:12,479] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 20:54:12,779] - ThreadPool::destroy(): waiting for thread(2)[0x4711a0,0x471138,], try=1
 DEBUG root [2018-06-29 20:54:13,184] - TPThread::~TPThread(): 0x4711a0
 DEBUG root [2018-06-29 20:54:13,185] - TPThread::~TPThread(): 0x471138
 DEBUG root [2018-06-29 20:54:13,189] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-29 20:54:13,291] - Bundle::destroyObjPool(): size 12.
 DEBUG root [2018-06-29 20:54:13,292] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-06-29 20:54:13,300] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-06-29 20:54:13,301] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-06-29 20:54:13,301] - EndPoint::destroyObjPool(): size 14.
 DEBUG root [2018-06-29 20:54:13,301] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-06-29 20:54:13,302] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-06-29 20:54:13,307] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-06-29 20:54:13,308] - loginapp(9000) has shut down.
  INFO root [2018-06-29 20:54:19,473] - 
  INFO root [2018-06-29 20:54:19,475] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:54:19,477] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:54:19,478] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:54:19,479] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:54:19,493] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:54:19,494] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:54:19,499] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15181 )
  INFO root [2018-06-29 20:54:19,503] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15181, SOMAXCONN=128.
  INFO root [2018-06-29 20:54:19,503] - server-configs:
  INFO root [2018-06-29 20:54:19,503] - 	internalAddr : 192.168.31.56:15181
  INFO root [2018-06-29 20:54:19,504] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:54:19,504] - 	componentID : 9000
  INFO root [2018-06-29 20:54:21,858] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 22045. PID: 8272 ----
  INFO root [2018-06-29 20:54:21,862] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:54:21,863] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:54:21,863] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:54:22,127] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:54:22,129] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:54:22,130] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:54:22,139] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:54:22,140] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:54:22,140] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:54:22,145] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:54:22,513] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:54:22,731] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:54:22,734] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:54:22,740] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:54:22,741] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:54:24,096] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:54:24,098] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:54:31,281] - Components::findComponents: find logger(1)...
  WARN root [2018-06-29 20:54:31,592] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20019, errorno=10048
  INFO root [2018-06-29 20:54:32,601] - Components::findComponents: find logger(2)...
  INFO root [2018-06-29 20:54:32,628] - Components::findComponents: found logger, addr:192.168.31.56:15178
  INFO root [2018-06-29 20:54:32,630] - Components::addComponent: reset orderLog, uid=22045!
  INFO root [2018-06-29 20:54:32,630] - Components::addComponent[logger], uid=22045, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:54:32,636] - Components::findComponents: find dbmgr(3)...
  INFO root [2018-06-29 20:54:32,733] - Components::findComponents: found dbmgr, addr:192.168.31.56:15180
  INFO root [2018-06-29 20:54:32,733] - Components::addComponent: reset orderLog, uid=22045!
  INFO root [2018-06-29 20:54:32,733] - Components::addComponent[dbmgr], uid=22045, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:54:32,735] - Components::findComponents: found dbmgr, addr:192.168.31.56:15180
  WARN root [2018-06-29 20:54:33,735] - Forwarding logs to logger[192.168.31.56:15178/0/0/0]...
 ERROR root [2018-06-29 20:56:08,103] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:56:08,124] - The following logs sent to logger failed:
  WARN root [2018-06-29 20:56:08,125] - ==> [2018-06-29 20:56:08 102] TCPPacketReceiver::processPendingEvents(192.168.31.56:15178): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:56:08,125] - ==> [2018-06-29 20:56:08 104] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 20:56:08,240] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15180): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 20:56:08,253] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 20:56:08,273] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 20:56:08,274] - onLoginAppShutDown()
  INFO root [2018-06-29 20:56:08,274] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 20:56:08,274] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 20:56:08,275] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:56:08,276] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:56:08,276] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:56:08,276] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:56:08,276] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:56:08,277] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:56:08,277] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:56:08,277] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:56:08,296] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 20:56:08,297] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 20:56:08,598] - ThreadPool::destroy(): waiting for thread(2)[0x442178,0x442110,], try=1
 DEBUG root [2018-06-29 20:56:08,998] - TPThread::~TPThread(): 0x442178
 DEBUG root [2018-06-29 20:56:08,999] - TPThread::~TPThread(): 0x442110
 DEBUG root [2018-06-29 20:56:09,000] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-29 20:56:09,042] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-06-29 20:56:09,043] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-06-29 20:56:09,044] - TCPPacket::destroyObjPool(): size 27.
 DEBUG root [2018-06-29 20:56:09,045] - UDPPacket::destroyObjPool(): size 15.
 DEBUG root [2018-06-29 20:56:09,046] - EndPoint::destroyObjPool(): size 14.
 DEBUG root [2018-06-29 20:56:09,046] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-06-29 20:56:09,047] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-06-29 20:56:09,047] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-06-29 20:56:09,048] - loginapp(9000) has shut down.
  INFO root [2018-06-29 20:59:00,130] - 
  INFO root [2018-06-29 20:59:00,140] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 20:59:00,142] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 20:59:00,142] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 20:59:00,142] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 20:59:00,176] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 20:59:00,177] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 20:59:00,199] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15298 )
  INFO root [2018-06-29 20:59:00,200] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15298, SOMAXCONN=128.
  INFO root [2018-06-29 20:59:00,200] - server-configs:
  INFO root [2018-06-29 20:59:00,200] - 	internalAddr : 192.168.31.56:15298
  INFO root [2018-06-29 20:59:00,201] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 20:59:00,201] - 	componentID : 9000
  INFO root [2018-06-29 20:59:02,302] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 22962. PID: 3288 ----
  INFO root [2018-06-29 20:59:02,303] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 20:59:02,304] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 20:59:02,304] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 20:59:02,527] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 20:59:02,529] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 20:59:02,530] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 20:59:02,537] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 20:59:02,538] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 20:59:02,538] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 20:59:02,540] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 20:59:02,724] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 20:59:02,877] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 20:59:02,877] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 20:59:02,915] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 20:59:02,916] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 20:59:04,454] - ---- loginapp is running ----
 DEBUG root [2018-06-29 20:59:04,455] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 20:59:11,616] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 20:59:11,653] - Components::findComponents: found logger, addr:192.168.31.56:15304
  INFO root [2018-06-29 20:59:11,653] - Components::addComponent: reset orderLog, uid=22962!
  INFO root [2018-06-29 20:59:11,653] - Components::addComponent[logger], uid=22962, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:59:11,655] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 20:59:11,759] - Components::findComponents: found dbmgr, addr:192.168.31.56:15301
  INFO root [2018-06-29 20:59:11,759] - Components::addComponent: reset orderLog, uid=22962!
  INFO root [2018-06-29 20:59:11,759] - Components::addComponent[dbmgr], uid=22962, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 20:59:11,760] - Components::findComponents: found dbmgr, addr:192.168.31.56:15301
  WARN root [2018-06-29 20:59:12,760] - Forwarding logs to logger[192.168.31.56:15304/0/0/0]...
 ERROR root [2018-06-29 21:14:10,041] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:14:10,052] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:14:10,052] - ==> [2018-06-29 21:14:10 038] TCPPacketReceiver::processPendingEvents(192.168.31.56:15304): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:14:10,053] - ==> [2018-06-29 21:14:10 042] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 21:14:10,168] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15301): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:14:10,173] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:14:10,176] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 21:14:10,180] - onLoginAppShutDown()
  INFO root [2018-06-29 21:14:10,180] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 21:14:10,181] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 21:14:10,182] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:14:10,182] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:14:10,182] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:14:10,183] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:14:10,183] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:14:10,183] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:14:10,184] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:14:10,184] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:14:10,202] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 21:14:10,203] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 21:14:10,503] - ThreadPool::destroy(): waiting for thread(2)[0x7411a0,0x741138,], try=1
  INFO root [2018-06-29 21:14:14,633] - 
  INFO root [2018-06-29 21:14:14,666] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:14:14,668] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:14:14,669] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:14:14,670] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:14:14,708] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:14:14,708] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:14:14,713] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15517 )
  INFO root [2018-06-29 21:14:14,714] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15517, SOMAXCONN=128.
  INFO root [2018-06-29 21:14:14,715] - server-configs:
  INFO root [2018-06-29 21:14:14,715] - 	internalAddr : 192.168.31.56:15517
  INFO root [2018-06-29 21:14:14,715] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:14:14,716] - 	componentID : 9000
  WARN root [2018-06-29 21:14:15,957] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20013, errorno=10048
  INFO root [2018-06-29 21:14:15,966] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 25947. PID: 5204 ----
  INFO root [2018-06-29 21:14:15,967] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:14:15,967] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:14:15,968] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:14:16,137] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:14:16,138] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:14:16,140] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:14:16,148] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:14:16,149] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:14:16,149] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:14:16,150] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:14:16,240] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:14:16,359] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:14:16,359] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:14:16,368] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:14:16,372] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:14:18,520] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:14:18,522] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 21:14:25,728] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 21:14:25,762] - Components::findComponents: found logger, addr:192.168.31.56:15522
  INFO root [2018-06-29 21:14:25,764] - Components::addComponent: reset orderLog, uid=25947!
  INFO root [2018-06-29 21:14:25,765] - Components::addComponent[logger], uid=25947, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:14:25,781] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 21:14:25,880] - Components::findComponents: found dbmgr, addr:192.168.31.56:15515
  INFO root [2018-06-29 21:14:25,881] - Components::addComponent: reset orderLog, uid=25947!
  INFO root [2018-06-29 21:14:25,882] - Components::addComponent[dbmgr], uid=25947, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:14:25,886] - Components::findComponents: found dbmgr, addr:192.168.31.56:15515
  WARN root [2018-06-29 21:14:26,887] - Forwarding logs to logger[192.168.31.56:15522/0/0/0]...
 ERROR root [2018-06-29 21:16:36,933] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:16:36,947] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:16:36,948] - ==> [2018-06-29 21:16:36 928] TCPPacketReceiver::processPendingEvents(192.168.31.56:15522): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:16:36,948] - ==> [2018-06-29 21:16:36 934] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 21:16:37,039] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15515): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:16:37,045] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:16:37,055] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 21:16:37,063] - onLoginAppShutDown()
  INFO root [2018-06-29 21:16:37,063] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 21:16:37,064] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 21:16:37,065] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:16:37,066] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:16:37,066] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:16:37,066] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:16:37,067] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:16:37,067] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:16:37,067] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:16:37,067] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:16:37,085] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 21:16:37,086] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 21:16:37,386] - ThreadPool::destroy(): waiting for thread(2)[0x8d1208,0x8d11a0,], try=1
  INFO root [2018-06-29 21:16:44,837] - 
  INFO root [2018-06-29 21:16:44,838] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:16:44,840] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:16:44,841] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:16:44,841] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:16:44,854] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:16:44,855] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:16:44,859] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15611 )
  INFO root [2018-06-29 21:16:44,860] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15611, SOMAXCONN=128.
  INFO root [2018-06-29 21:16:44,860] - server-configs:
  INFO root [2018-06-29 21:16:44,860] - 	internalAddr : 192.168.31.56:15611
  INFO root [2018-06-29 21:16:44,861] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:16:44,861] - 	componentID : 9000
  INFO root [2018-06-29 21:16:46,953] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 26437. PID: 1748 ----
  INFO root [2018-06-29 21:16:46,958] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:16:46,958] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:16:46,959] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:16:47,167] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:16:47,169] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:16:47,170] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:16:47,177] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:16:47,178] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:16:47,178] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:16:47,180] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:16:47,290] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:16:47,418] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:16:47,418] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:16:47,423] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:16:47,424] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:16:48,967] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:16:48,969] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 21:16:54,019] - 
  INFO root [2018-06-29 21:16:54,020] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:16:54,022] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:16:54,023] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:16:54,023] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:16:54,063] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:16:54,063] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:16:54,073] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15631 )
  INFO root [2018-06-29 21:16:54,073] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15631, SOMAXCONN=128.
  INFO root [2018-06-29 21:16:54,074] - server-configs:
  INFO root [2018-06-29 21:16:54,074] - 	internalAddr : 192.168.31.56:15631
  INFO root [2018-06-29 21:16:54,074] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:16:54,075] - 	componentID : 9000
  INFO root [2018-06-29 21:16:56,341] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 26466. PID: 8540 ----
  INFO root [2018-06-29 21:16:56,342] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:16:56,343] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:16:56,343] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:16:56,521] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:16:56,554] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:16:56,556] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:16:56,563] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:16:56,564] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:16:56,565] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:16:56,566] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:16:56,656] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:16:56,741] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:16:56,742] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:16:56,746] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:16:56,748] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:16:57,974] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:16:57,975] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 21:17:05,146] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 21:17:05,172] - Components::findComponents: found logger, addr:192.168.31.56:15627
  INFO root [2018-06-29 21:17:05,172] - Components::addComponent: reset orderLog, uid=26466!
  INFO root [2018-06-29 21:17:05,172] - Components::addComponent[logger], uid=26466, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:17:05,174] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 21:17:05,277] - Components::findComponents: found dbmgr, addr:192.168.31.56:15625
  INFO root [2018-06-29 21:17:05,277] - Components::addComponent: reset orderLog, uid=26466!
  INFO root [2018-06-29 21:17:05,277] - Components::addComponent[dbmgr], uid=26466, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:17:05,278] - Components::findComponents: found dbmgr, addr:192.168.31.56:15625
  WARN root [2018-06-29 21:17:06,278] - Forwarding logs to logger[192.168.31.56:15627/0/0/0]...
 ERROR root [2018-06-29 21:21:31,413] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:21:31,425] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:21:31,426] - ==> [2018-06-29 21:21:31 411] TCPPacketReceiver::processPendingEvents(192.168.31.56:15627): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:21:31,427] - ==> [2018-06-29 21:21:31 416] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 21:21:31,535] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15625): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:21:31,536] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:21:31,537] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 21:21:31,539] - onLoginAppShutDown()
  INFO root [2018-06-29 21:21:31,540] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 21:21:31,540] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 21:21:31,541] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:21:31,541] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:21:31,542] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:21:31,542] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:21:31,542] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:21:31,542] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:21:31,543] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:21:31,543] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:21:31,562] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 21:21:31,562] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 21:21:31,862] - ThreadPool::destroy(): waiting for thread(2)[0x16411a0,0x1641138,], try=1
  INFO root [2018-06-29 21:21:36,451] - 
  INFO root [2018-06-29 21:21:36,458] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:21:36,460] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:21:36,461] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:21:36,462] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:21:36,489] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:21:36,490] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:21:36,533] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15736 )
  INFO root [2018-06-29 21:21:36,534] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15736, SOMAXCONN=128.
  INFO root [2018-06-29 21:21:36,534] - server-configs:
  INFO root [2018-06-29 21:21:36,534] - 	internalAddr : 192.168.31.56:15736
  INFO root [2018-06-29 21:21:36,535] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:21:36,535] - 	componentID : 9000
  INFO root [2018-06-29 21:21:37,506] - Components::findLogger: found logger, addr:192.168.31.56:15729
  INFO root [2018-06-29 21:21:37,508] - Components::addComponent: reset orderLog, uid=27390!
  INFO root [2018-06-29 21:21:37,508] - Components::addComponent[logger], uid=27390, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:21:37,519] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27390. PID: 8340 ----
  INFO root [2018-06-29 21:21:37,520] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:21:37,520] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:21:37,521] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:21:37,679] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:21:37,680] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:21:37,681] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:21:37,688] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:21:37,689] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:21:37,689] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:21:37,691] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:21:37,759] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:21:37,816] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:21:37,816] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:21:37,820] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:21:37,822] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:21:38,985] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:21:38,986] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 21:21:44,257] - 
  INFO root [2018-06-29 21:21:44,258] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:21:44,260] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:21:44,261] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:21:44,261] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:21:44,297] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:21:44,298] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:21:44,302] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15751 )
  INFO root [2018-06-29 21:21:44,303] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15751, SOMAXCONN=128.
  INFO root [2018-06-29 21:21:44,303] - server-configs:
  INFO root [2018-06-29 21:21:44,304] - 	internalAddr : 192.168.31.56:15751
  INFO root [2018-06-29 21:21:44,304] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:21:44,304] - 	componentID : 9000
  INFO root [2018-06-29 21:21:45,939] - Components::findLogger: found logger, addr:192.168.31.56:15758
  INFO root [2018-06-29 21:21:45,940] - Components::addComponent: reset orderLog, uid=27417!
  INFO root [2018-06-29 21:21:45,940] - Components::addComponent[logger], uid=27417, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:21:45,960] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27417. PID: 11656 ----
  INFO root [2018-06-29 21:21:45,960] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:21:45,962] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:21:45,963] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:21:46,228] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:21:46,229] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:21:46,230] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:21:46,238] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:21:46,239] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:21:46,239] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:21:46,241] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:21:46,413] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:21:47,187] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:21:47,188] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:21:47,212] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:21:47,216] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:21:48,839] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:21:48,842] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 21:21:54,959] - Forwarding logs to logger[192.168.31.56:15758/0/0/0]...
 ERROR root [2018-06-29 21:21:59,117] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:21:59,121] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:21:59,121] - ==> [2018-06-29 21:21:59 116] TCPPacketReceiver::processPendingEvents(192.168.31.56:15758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:21:59,122] - ==> [2018-06-29 21:21:59 118] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:22:03,766] - 
  INFO root [2018-06-29 21:22:03,767] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:22:03,772] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:22:03,773] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:22:03,774] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:22:03,803] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:22:03,803] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:22:03,808] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15781 )
  INFO root [2018-06-29 21:22:03,808] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15781, SOMAXCONN=128.
  INFO root [2018-06-29 21:22:03,809] - server-configs:
  INFO root [2018-06-29 21:22:03,809] - 	internalAddr : 192.168.31.56:15781
  INFO root [2018-06-29 21:22:03,809] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:22:03,809] - 	componentID : 9000
  INFO root [2018-06-29 21:22:05,916] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27479. PID: 660 ----
  INFO root [2018-06-29 21:22:05,918] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:22:05,918] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:22:05,919] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:22:06,294] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:22:06,296] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:22:06,297] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:22:06,305] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:22:06,306] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:22:06,306] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:22:06,308] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:22:06,474] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:22:06,623] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:22:06,624] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:22:06,634] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:22:06,636] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:22:07,511] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:22:07,513] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 21:22:14,673] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 21:22:14,771] - Components::findComponents: found logger, addr:192.168.31.56:15775
  INFO root [2018-06-29 21:22:14,771] - Components::addComponent: reset orderLog, uid=27479!
  INFO root [2018-06-29 21:22:14,771] - Components::addComponent[logger], uid=27479, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:22:14,773] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 21:22:14,875] - Components::findComponents: found dbmgr, addr:192.168.31.56:15777
  INFO root [2018-06-29 21:22:14,875] - Components::addComponent: reset orderLog, uid=27479!
  INFO root [2018-06-29 21:22:14,875] - Components::addComponent[dbmgr], uid=27479, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:22:14,876] - Components::findComponents: found dbmgr, addr:192.168.31.56:15777
  WARN root [2018-06-29 21:22:15,876] - Forwarding logs to logger[192.168.31.56:15775/0/0/0]...
 ERROR root [2018-06-29 21:22:19,841] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:22:19,856] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:22:19,857] - ==> [2018-06-29 21:22:19 835] TCPPacketReceiver::processPendingEvents(192.168.31.56:15775): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:22:19,858] - ==> [2018-06-29 21:22:19 842] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 21:22:19,949] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15777): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:22:19,954] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:22:19,969] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 21:22:19,978] - onLoginAppShutDown()
  INFO root [2018-06-29 21:22:19,978] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 21:22:19,978] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 21:22:19,979] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:22:19,980] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:22:19,980] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:22:19,980] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:22:19,981] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:22:19,981] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:22:19,981] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:22:19,982] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:22:19,999] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 21:22:19,999] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 21:22:20,299] - ThreadPool::destroy(): waiting for thread(2)[0x1782178,0x1782110,], try=1
  INFO root [2018-06-29 21:22:55,319] - 
  INFO root [2018-06-29 21:22:55,321] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:22:55,323] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:22:55,323] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:22:55,324] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:22:55,337] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:22:55,338] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:22:55,343] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15813 )
  INFO root [2018-06-29 21:22:55,343] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15813, SOMAXCONN=128.
  INFO root [2018-06-29 21:22:55,344] - server-configs:
  INFO root [2018-06-29 21:22:55,345] - 	internalAddr : 192.168.31.56:15813
  INFO root [2018-06-29 21:22:55,345] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:22:55,345] - 	componentID : 9000
  INFO root [2018-06-29 21:22:57,432] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27645. PID: 11748 ----
  INFO root [2018-06-29 21:22:57,443] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:22:57,443] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:22:57,444] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:22:57,612] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:22:57,614] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:22:57,615] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:22:57,622] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:22:57,623] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:22:57,623] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:22:57,624] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:22:57,706] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:22:57,786] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:22:57,786] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:22:57,791] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:22:57,792] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:22:58,654] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:22:58,654] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 21:23:05,792] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 21:23:05,792] - Components::findComponents: found logger, addr:192.168.31.56:15808
  INFO root [2018-06-29 21:23:05,792] - Components::addComponent: reset orderLog, uid=27645!
  INFO root [2018-06-29 21:23:05,792] - Components::addComponent[logger], uid=27645, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:23:05,792] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 21:23:05,792] - Components::findComponents: found dbmgr, addr:192.168.31.56:15807
  INFO root [2018-06-29 21:23:05,792] - Components::addComponent: reset orderLog, uid=27645!
  INFO root [2018-06-29 21:23:05,792] - Components::addComponent[dbmgr], uid=27645, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:23:05,792] - Components::findComponents: found dbmgr, addr:192.168.31.56:15807
  WARN root [2018-06-29 21:23:06,992] - Forwarding logs to logger[192.168.31.56:15808/0/0/0]...
 ERROR root [2018-06-29 21:23:09,105] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:23:09,105] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:23:09,105] - ==> [2018-06-29 21:23:09 104] TCPPacketReceiver::processPendingEvents(192.168.31.56:15808): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:23:09,105] - ==> [2018-06-29 21:23:09 105] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:23:31,229] - 
  INFO root [2018-06-29 21:23:31,232] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:23:31,235] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:23:31,235] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:23:31,236] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:23:31,270] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:23:31,271] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:23:31,284] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15842 )
  INFO root [2018-06-29 21:23:31,285] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15842, SOMAXCONN=128.
  INFO root [2018-06-29 21:23:31,285] - server-configs:
  INFO root [2018-06-29 21:23:31,285] - 	internalAddr : 192.168.31.56:15842
  INFO root [2018-06-29 21:23:31,286] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:23:31,286] - 	componentID : 9000
  INFO root [2018-06-29 21:23:32,577] - Components::findLogger: found logger, addr:192.168.31.56:15837
  INFO root [2018-06-29 21:23:32,578] - Components::addComponent: reset orderLog, uid=27766!
  INFO root [2018-06-29 21:23:32,578] - Components::addComponent[logger], uid=27766, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:23:32,599] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27766. PID: 11784 ----
  INFO root [2018-06-29 21:23:32,600] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:23:32,601] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:23:32,602] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:23:32,775] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:23:32,776] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:23:32,777] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:23:32,784] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:23:32,784] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:23:32,785] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:23:32,786] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:23:32,876] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:23:32,999] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:23:32,999] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:23:33,004] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:23:33,006] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:23:34,133] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:23:34,134] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 21:23:40,255] - Forwarding logs to logger[192.168.31.56:15837/0/0/0]...
 ERROR root [2018-06-29 21:23:40,658] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:23:40,660] - The following logs sent to logger failed:
  WARN root [2018-06-29 21:23:40,661] - ==> [2018-06-29 21:23:40 657] TCPPacketReceiver::processPendingEvents(192.168.31.56:15837): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 21:23:40,661] - ==> [2018-06-29 21:23:40 658] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 21:24:09,648] - 
  INFO root [2018-06-29 21:24:09,650] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 21:24:09,652] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 21:24:09,654] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 21:24:09,654] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 21:24:09,705] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 21:24:09,707] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 21:24:09,711] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15878 )
  INFO root [2018-06-29 21:24:09,712] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15878, SOMAXCONN=128.
  INFO root [2018-06-29 21:24:09,712] - server-configs:
  INFO root [2018-06-29 21:24:09,713] - 	internalAddr : 192.168.31.56:15878
  INFO root [2018-06-29 21:24:09,713] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 21:24:09,713] - 	componentID : 9000
  INFO root [2018-06-29 21:24:10,479] - Components::findLogger: found logger, addr:192.168.31.56:15875
  INFO root [2018-06-29 21:24:10,479] - Components::addComponent: reset orderLog, uid=27890!
  INFO root [2018-06-29 21:24:10,479] - Components::addComponent[logger], uid=27890, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 21:24:10,488] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27890. PID: 8388 ----
  INFO root [2018-06-29 21:24:10,489] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 21:24:10,490] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 21:24:10,490] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 21:24:10,639] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 21:24:10,640] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 21:24:10,641] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 21:24:10,647] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 21:24:10,648] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 21:24:10,648] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 21:24:10,649] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 21:24:10,706] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 21:24:10,768] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 21:24:10,768] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 21:24:10,771] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 21:24:10,772] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 21:24:11,380] - ---- loginapp is running ----
 DEBUG root [2018-06-29 21:24:11,381] - Components::process(): Request for the process of identity...
  WARN root [2018-06-29 21:24:17,546] - Forwarding logs to logger[192.168.31.56:15875/0/0/0]...
 ERROR root [2018-06-29 23:11:39,892] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 23:11:39,905] - The following logs sent to logger failed:
  WARN root [2018-06-29 23:11:39,906] - ==> [2018-06-29 23:11:39 890] TCPPacketReceiver::processPendingEvents(192.168.31.56:15875): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 23:11:39,907] - ==> [2018-06-29 23:11:39 893] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 23:11:40,017] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15879): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 23:11:40,021] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 23:11:40,029] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 23:11:40,036] - onLoginAppShutDown()
  INFO root [2018-06-29 23:11:40,036] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 23:11:40,037] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 23:11:40,037] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 23:11:40,038] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 23:11:40,038] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 23:11:40,038] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 23:11:40,039] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 23:11:40,039] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 23:11:40,039] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 23:11:40,040] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 23:11:40,058] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 23:11:40,059] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 23:11:40,360] - ThreadPool::destroy(): waiting for thread(2)[0x8211a0,0x821138,], try=1
  INFO root [2018-06-29 23:11:45,144] - 
  INFO root [2018-06-29 23:11:45,145] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-29 23:11:45,146] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-29 23:11:45,147] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-29 23:11:45,148] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-29 23:11:45,156] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-29 23:11:45,157] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-29 23:11:45,160] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:17479 )
  INFO root [2018-06-29 23:11:45,160] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:17479, SOMAXCONN=128.
  INFO root [2018-06-29 23:11:45,161] - server-configs:
  INFO root [2018-06-29 23:11:45,161] - 	internalAddr : 192.168.31.56:17479
  INFO root [2018-06-29 23:11:45,161] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-29 23:11:45,161] - 	componentID : 9000
  INFO root [2018-06-29 23:11:47,269] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 16205. PID: 6324 ----
  INFO root [2018-06-29 23:11:47,270] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-29 23:11:47,271] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-29 23:11:47,272] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-29 23:11:47,490] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 23:11:47,492] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 23:11:47,493] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 23:11:47,500] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 23:11:47,501] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 23:11:47,501] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 23:11:47,503] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 23:11:47,702] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 23:11:47,893] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-29 23:11:47,893] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-29 23:11:47,899] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-29 23:11:47,900] - TelnetServer server is running on port 31000
  INFO root [2018-06-29 23:11:49,345] - ---- loginapp is running ----
 DEBUG root [2018-06-29 23:11:49,348] - Components::process(): Request for the process of identity...
  INFO root [2018-06-29 23:11:56,699] - Components::findComponents: find logger(1)...
  INFO root [2018-06-29 23:11:56,707] - Components::findComponents: found logger, addr:192.168.31.56:17481
  INFO root [2018-06-29 23:11:56,707] - Components::addComponent: reset orderLog, uid=16205!
  INFO root [2018-06-29 23:11:56,708] - Components::addComponent[logger], uid=16205, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 23:11:56,712] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-29 23:11:56,813] - Components::findComponents: found dbmgr, addr:192.168.31.56:17484
  INFO root [2018-06-29 23:11:56,814] - Components::addComponent: reset orderLog, uid=16205!
  INFO root [2018-06-29 23:11:56,814] - Components::addComponent[dbmgr], uid=16205, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-29 23:11:56,815] - Components::findComponents: found dbmgr, addr:192.168.31.56:17484
  WARN root [2018-06-29 23:11:57,817] - Forwarding logs to logger[192.168.31.56:17481/0/0/0]...
 ERROR root [2018-06-29 23:50:25,447] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 23:50:25,447] - The following logs sent to logger failed:
  WARN root [2018-06-29 23:50:25,447] - ==> [2018-06-29 23:50:25 447] TCPPacketReceiver::processPendingEvents(192.168.31.56:17481): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 23:50:25,447] - ==> [2018-06-29 23:50:25 447] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-29 23:50:25,525] - TCPPacketReceiver::processPendingEvents(192.168.31.56:17484): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-29 23:50:25,525] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-29 23:50:25,525] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-29 23:50:25,525] - onLoginAppShutDown()
  INFO root [2018-06-29 23:50:25,525] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-29 23:50:25,525] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-29 23:50:25,525] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-29 23:50:25,525] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-29 23:50:25,525] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-29 23:50:25,525] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-29 23:50:25,525] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-29 23:50:25,541] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-29 23:50:25,541] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-29 23:50:25,541] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-29 23:50:25,556] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-29 23:50:25,556] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-29 23:50:25,868] - ThreadPool::destroy(): waiting for thread(2)[0x6511a0,0x651138,], try=1
