  INFO root [2018-06-28 15:31:33,738] - 
  INFO root [2018-06-28 15:31:33,739] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 15:31:36,810] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 15:31:36,811] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 15:31:36,811] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 15:31:37,260] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 15:31:37,260] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 15:31:37,263] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13670 )
  INFO root [2018-06-28 15:31:37,264] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13670, SOMAXCONN=128.
  INFO root [2018-06-28 15:31:37,264] - server-configs:
  INFO root [2018-06-28 15:31:37,264] - 	internalAddr : 192.168.31.56:13670
  INFO root [2018-06-28 15:31:37,264] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 15:31:37,264] - 	componentID : 9000
  INFO root [2018-06-28 15:31:39,419] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4282. PID: 5336 ----
  INFO root [2018-06-28 15:31:39,420] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 15:31:39,487] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 15:31:39,488] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 15:31:44,751] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 15:31:44,953] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 15:31:45,086] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 15:31:46,746] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 15:31:46,832] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 15:31:46,877] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 15:31:47,036] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 15:31:49,134] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 15:31:51,804] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 15:31:51,805] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 15:31:52,115] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 15:31:52,155] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 15:31:53,242] - ---- loginapp is running ----
 DEBUG root [2018-06-28 15:31:53,327] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 15:32:00,756] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 15:32:00,817] - Components::findComponents: found logger, addr:192.168.31.56:13666
  INFO root [2018-06-28 15:32:00,817] - Components::addComponent: reset orderLog, uid=4282!
  INFO root [2018-06-28 15:32:00,817] - Components::addComponent[logger], uid=4282, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 15:32:00,820] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 15:32:00,922] - Components::findComponents: found dbmgr, addr:192.168.31.56:13673
  INFO root [2018-06-28 15:32:00,922] - Components::addComponent: reset orderLog, uid=4282!
  INFO root [2018-06-28 15:32:00,922] - Components::addComponent[dbmgr], uid=4282, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 15:32:00,923] - Components::findComponents: found dbmgr, addr:192.168.31.56:13673
  WARN root [2018-06-28 15:32:01,923] - Forwarding logs to logger[192.168.31.56:13666/0/0/0]...
 ERROR root [2018-06-28 15:32:04,343] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 15:32:04,356] - The following logs sent to logger failed:
  WARN root [2018-06-28 15:32:04,377] - ==> [2018-06-28 15:32:04 342] TCPPacketReceiver::processPendingEvents(192.168.31.56:13666): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 15:32:04,378] - ==> [2018-06-28 15:32:04 344] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 15:32:04,991] - Components::findComponents: register self to dbmgr...
  INFO root [2018-06-28 15:32:08,941] - 
  INFO root [2018-06-28 15:32:08,942] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 15:32:08,944] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 15:32:08,945] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 15:32:08,946] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 15:32:08,969] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 15:32:08,970] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 15:32:08,977] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:13693 )
  INFO root [2018-06-28 15:32:08,977] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:13693, SOMAXCONN=128.
  INFO root [2018-06-28 15:32:08,978] - server-configs:
  INFO root [2018-06-28 15:32:08,978] - 	internalAddr : 192.168.31.56:13693
  INFO root [2018-06-28 15:32:08,978] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 15:32:08,979] - 	componentID : 9000
  INFO root [2018-06-28 15:32:11,249] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4455. PID: 5200 ----
  INFO root [2018-06-28 15:32:11,250] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 15:32:11,251] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 15:32:11,251] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 15:32:11,611] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 15:32:11,612] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 15:32:11,613] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 15:32:11,621] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 15:32:11,622] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 15:32:11,622] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 15:32:11,624] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 15:32:11,917] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 15:32:12,220] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 15:32:12,221] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 15:32:12,227] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 15:32:12,229] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 15:32:14,704] - ---- loginapp is running ----
 DEBUG root [2018-06-28 15:32:14,706] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 15:32:22,028] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 15:32:22,101] - Components::findComponents: found logger, addr:192.168.31.56:13700
  INFO root [2018-06-28 15:32:22,101] - Components::addComponent: reset orderLog, uid=4455!
  INFO root [2018-06-28 15:32:22,102] - Components::addComponent[logger], uid=4455, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 15:32:22,109] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 15:32:22,212] - Components::findComponents: found dbmgr, addr:192.168.31.56:13698
  INFO root [2018-06-28 15:32:22,212] - Components::addComponent: reset orderLog, uid=4455!
  INFO root [2018-06-28 15:32:22,212] - Components::addComponent[dbmgr], uid=4455, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 15:32:22,213] - Components::findComponents: found dbmgr, addr:192.168.31.56:13698
  WARN root [2018-06-28 15:32:23,213] - Forwarding logs to logger[192.168.31.56:13700/0/0/0]...
 ERROR root [2018-06-28 15:52:28,713] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 15:52:28,726] - The following logs sent to logger failed:
  WARN root [2018-06-28 15:52:28,727] - ==> [2018-06-28 15:52:28 707] TCPPacketReceiver::processPendingEvents(192.168.31.56:13700): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 15:52:28,727] - ==> [2018-06-28 15:52:28 715] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 15:52:28,843] - TCPPacketReceiver::processPendingEvents(192.168.31.56:13698): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 15:52:28,850] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 15:52:28,855] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 15:52:28,856] - onLoginAppShutDown()
  INFO root [2018-06-28 15:52:28,857] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 15:52:28,857] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 15:52:28,868] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 15:52:28,869] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 15:52:28,869] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 15:52:28,869] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 15:52:28,869] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 15:52:28,869] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 15:52:28,870] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 15:52:28,870] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 15:52:28,939] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 15:52:28,939] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 15:52:29,239] - ThreadPool::destroy(): waiting for thread(2)[0x6ebdf0,0x6ebd88,], try=1
  INFO root [2018-06-28 16:23:25,267] - 
  INFO root [2018-06-28 16:23:25,267] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 16:23:25,269] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 16:23:25,269] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 16:23:25,269] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 16:23:25,279] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 16:23:25,279] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 16:23:25,282] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:14991 )
  INFO root [2018-06-28 16:23:25,282] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:14991, SOMAXCONN=128.
  INFO root [2018-06-28 16:23:25,282] - server-configs:
  INFO root [2018-06-28 16:23:25,283] - 	internalAddr : 192.168.31.56:14991
  INFO root [2018-06-28 16:23:25,283] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 16:23:25,283] - 	componentID : 9000
  INFO root [2018-06-28 16:23:27,427] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 14500. PID: 10860 ----
  INFO root [2018-06-28 16:23:27,428] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 16:23:27,429] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 16:23:27,429] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 16:23:27,606] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 16:23:27,608] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 16:23:27,609] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 16:23:27,617] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 16:23:27,618] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 16:23:27,619] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 16:23:27,620] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 16:23:27,715] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 16:23:27,792] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 16:23:27,793] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 16:23:27,797] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 16:23:27,800] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 16:23:28,602] - ---- loginapp is running ----
 DEBUG root [2018-06-28 16:23:28,603] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 16:23:35,718] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 16:23:35,753] - Components::findComponents: found logger, addr:192.168.31.56:14998
  INFO root [2018-06-28 16:23:35,754] - Components::addComponent: reset orderLog, uid=14500!
  INFO root [2018-06-28 16:23:35,754] - Components::addComponent[logger], uid=14500, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 16:23:35,756] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-28 16:23:36,857] - Forwarding logs to logger[192.168.31.56:14998/0/0/0]...
  INFO root [2018-06-28 17:14:55,165] - 
  INFO root [2018-06-28 17:14:55,166] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:14:55,168] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:14:55,168] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:14:55,168] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:14:55,180] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:14:55,181] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:14:55,184] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16533 )
  INFO root [2018-06-28 17:14:55,184] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16533, SOMAXCONN=128.
  INFO root [2018-06-28 17:14:55,184] - server-configs:
  INFO root [2018-06-28 17:14:55,184] - 	internalAddr : 192.168.31.56:16533
  INFO root [2018-06-28 17:14:55,184] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:14:55,185] - 	componentID : 9000
  INFO root [2018-06-28 17:14:57,370] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 24591. PID: 12096 ----
  INFO root [2018-06-28 17:14:57,372] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:14:57,372] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:14:57,373] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:14:57,611] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:14:57,613] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:14:57,614] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:14:57,623] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:14:57,624] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:14:57,624] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:14:57,626] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:14:57,824] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:14:58,020] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:14:58,021] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:14:58,027] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:14:58,029] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:14:59,735] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:14:59,736] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 17:15:06,868] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 17:15:06,924] - Components::findComponents: found logger, addr:192.168.31.56:16538
  INFO root [2018-06-28 17:15:06,924] - Components::addComponent: reset orderLog, uid=24591!
  INFO root [2018-06-28 17:15:06,924] - Components::addComponent[logger], uid=24591, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:15:06,926] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 17:15:07,028] - Components::findComponents: found dbmgr, addr:192.168.31.56:16540
  INFO root [2018-06-28 17:15:07,028] - Components::addComponent: reset orderLog, uid=24591!
  INFO root [2018-06-28 17:15:07,028] - Components::addComponent[dbmgr], uid=24591, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:15:07,029] - Components::findComponents: found dbmgr, addr:192.168.31.56:16540
  WARN root [2018-06-28 17:15:08,030] - Forwarding logs to logger[192.168.31.56:16538/0/0/0]...
 ERROR root [2018-06-28 17:15:11,065] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:15:11,072] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:15:11,073] - ==> [2018-06-28 17:15:11 063] TCPPacketReceiver::processPendingEvents(192.168.31.56:16538): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:15:11,074] - ==> [2018-06-28 17:15:11 066] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:15:11,108] - Components::findComponents: register self to dbmgr...
  INFO root [2018-06-28 17:15:11,128] - Components::findComponents: register self to baseappmgr...
  INFO root [2018-06-28 17:15:11,146] - Components::process(): Found all the components!
  WARN root [2018-06-28 17:15:11,198] - TCPPacketReceiver::processPendingEvents(192.168.31.56:16540): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:15:11,200] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:15:11,202] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:15:11,202] - onLoginAppShutDown()
  INFO root [2018-06-28 17:15:11,203] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:15:11,203] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:15:11,204] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:15:11,204] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:15:11,204] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:15:11,204] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:15:11,205] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:15:11,205] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:15:11,205] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:15:11,206] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:15:11,228] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:15:11,229] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:15:11,529] - ThreadPool::destroy(): waiting for thread(2)[0x6ebdd0,0x6ebd68,], try=1
  INFO root [2018-06-28 17:15:15,629] - 
  INFO root [2018-06-28 17:15:15,630] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:15:15,632] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:15:15,633] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:15:15,634] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:15:15,648] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:15:15,649] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:15:15,658] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16573 )
  INFO root [2018-06-28 17:15:15,658] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16573, SOMAXCONN=128.
  INFO root [2018-06-28 17:15:15,659] - server-configs:
  INFO root [2018-06-28 17:15:15,659] - 	internalAddr : 192.168.31.56:16573
  INFO root [2018-06-28 17:15:15,659] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:15:15,660] - 	componentID : 9000
  INFO root [2018-06-28 17:15:17,803] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 24656. PID: 11984 ----
  INFO root [2018-06-28 17:15:17,804] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:15:17,805] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:15:17,806] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:15:18,045] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:15:18,047] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:15:18,052] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:15:18,061] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:15:18,063] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:15:18,063] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:15:18,066] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:15:18,284] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:15:18,431] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:15:18,431] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:15:18,437] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:15:18,439] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:15:20,094] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:15:20,095] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 17:15:27,318] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 17:15:27,377] - Components::findComponents: found logger, addr:192.168.31.56:16575
  INFO root [2018-06-28 17:15:27,377] - Components::addComponent: reset orderLog, uid=24656!
  INFO root [2018-06-28 17:15:27,377] - Components::addComponent[logger], uid=24656, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:15:27,380] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 17:15:27,482] - Components::findComponents: found dbmgr, addr:192.168.31.56:16570
  INFO root [2018-06-28 17:15:27,482] - Components::addComponent: reset orderLog, uid=24656!
  INFO root [2018-06-28 17:15:27,482] - Components::addComponent[dbmgr], uid=24656, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:15:27,483] - Components::findComponents: found dbmgr, addr:192.168.31.56:16570
  WARN root [2018-06-28 17:15:28,483] - Forwarding logs to logger[192.168.31.56:16575/0/0/0]...
 ERROR root [2018-06-28 17:18:42,171] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:18:42,174] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:18:42,175] - ==> [2018-06-28 17:18:42 168] TCPPacketReceiver::processPendingEvents(192.168.31.56:16575): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:18:42,176] - ==> [2018-06-28 17:18:42 172] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 17:18:42,277] - TCPPacketReceiver::processPendingEvents(192.168.31.56:16570): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:18:42,281] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:18:42,287] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:18:42,289] - onLoginAppShutDown()
  INFO root [2018-06-28 17:18:42,290] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:18:42,290] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:18:42,291] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:18:42,291] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:18:42,292] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:18:42,292] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:18:42,292] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:18:42,293] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:18:42,293] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:18:42,293] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:18:42,312] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:18:42,313] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:18:42,613] - ThreadPool::destroy(): waiting for thread(2)[0x17bae08,0x17bada0,], try=1
  INFO root [2018-06-28 17:18:46,631] - 
  INFO root [2018-06-28 17:18:46,636] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:18:46,638] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:18:46,641] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:18:46,642] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:18:46,677] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:18:46,677] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:18:46,682] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16723 )
  INFO root [2018-06-28 17:18:46,682] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16723, SOMAXCONN=128.
  INFO root [2018-06-28 17:18:46,682] - server-configs:
  INFO root [2018-06-28 17:18:46,683] - 	internalAddr : 192.168.31.56:16723
  INFO root [2018-06-28 17:18:46,683] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:18:46,683] - 	componentID : 9000
  INFO root [2018-06-28 17:18:47,861] - Components::findLogger: found logger, addr:192.168.31.56:16719
  INFO root [2018-06-28 17:18:47,862] - Components::addComponent: reset orderLog, uid=25345!
  INFO root [2018-06-28 17:18:47,862] - Components::addComponent[logger], uid=25345, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:18:47,874] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 25345. PID: 7600 ----
  INFO root [2018-06-28 17:18:47,875] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:18:47,875] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:18:47,876] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:18:48,049] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:18:48,049] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:18:48,050] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:18:48,057] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:18:48,058] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:18:48,058] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:18:48,059] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:18:48,130] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:18:48,192] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:18:48,192] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:18:48,195] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:18:48,196] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:18:49,574] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:18:49,575] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 17:18:55,919] - Forwarding logs to logger[192.168.31.56:16719/0/0/0]...
 ERROR root [2018-06-28 17:23:05,986] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:23:05,997] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:23:05,998] - ==> [2018-06-28 17:23:05 982] TCPPacketReceiver::processPendingEvents(192.168.31.56:16719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:23:05,998] - ==> [2018-06-28 17:23:05 987] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 17:23:06,091] - TCPPacketReceiver::processPendingEvents(192.168.31.56:16722): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:23:06,097] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:23:06,116] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:23:06,117] - onLoginAppShutDown()
  INFO root [2018-06-28 17:23:06,117] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:23:06,118] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:23:06,118] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:23:06,119] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:23:06,119] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:23:06,119] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:23:06,120] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:23:06,120] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:23:06,120] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:23:06,121] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:23:06,139] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:23:06,139] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:23:06,439] - ThreadPool::destroy(): waiting for thread(2)[0x5dae08,0x5dada0,], try=1
  INFO root [2018-06-28 17:23:10,349] - 
  INFO root [2018-06-28 17:23:10,352] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:23:10,358] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:23:10,358] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:23:10,363] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:23:10,399] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:23:10,399] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:23:10,416] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16884 )
  INFO root [2018-06-28 17:23:10,416] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16884, SOMAXCONN=128.
  INFO root [2018-06-28 17:23:10,417] - server-configs:
  INFO root [2018-06-28 17:23:10,417] - 	internalAddr : 192.168.31.56:16884
  INFO root [2018-06-28 17:23:10,417] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:23:10,417] - 	componentID : 9000
  INFO root [2018-06-28 17:23:12,622] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 26204. PID: 4168 ----
  INFO root [2018-06-28 17:23:12,623] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:23:12,624] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:23:12,624] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:23:12,907] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:23:12,909] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:23:12,910] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:23:12,918] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:23:12,920] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:23:12,920] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:23:12,922] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:23:13,114] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:23:13,318] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:23:13,319] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:23:13,325] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:23:13,326] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:23:15,400] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:23:15,402] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 17:23:22,585] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 17:23:22,675] - Components::findComponents: found logger, addr:192.168.31.56:16892
  INFO root [2018-06-28 17:23:22,675] - Components::addComponent: reset orderLog, uid=26204!
  INFO root [2018-06-28 17:23:22,675] - Components::addComponent[logger], uid=26204, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:23:22,677] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 17:23:22,778] - Components::findComponents: found dbmgr, addr:192.168.31.56:16887
  INFO root [2018-06-28 17:23:22,779] - Components::addComponent: reset orderLog, uid=26204!
  INFO root [2018-06-28 17:23:22,779] - Components::addComponent[dbmgr], uid=26204, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:23:22,780] - Components::findComponents: found dbmgr, addr:192.168.31.56:16887
  WARN root [2018-06-28 17:23:23,780] - Forwarding logs to logger[192.168.31.56:16892/0/0/0]...
 ERROR root [2018-06-28 17:37:37,709] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:37:37,719] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:37:37,719] - ==> [2018-06-28 17:37:37 706] TCPPacketReceiver::processPendingEvents(192.168.31.56:16892): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:37:37,720] - ==> [2018-06-28 17:37:37 710] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 17:37:37,832] - TCPPacketReceiver::processPendingEvents(192.168.31.56:16887): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:37:37,837] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:37:37,843] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:37:37,844] - onLoginAppShutDown()
  INFO root [2018-06-28 17:37:37,844] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:37:37,844] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:37:37,845] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:37:37,846] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:37:37,846] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:37:37,846] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:37:37,847] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:37:37,847] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:37:37,847] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:37:37,848] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:37:37,866] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:37:37,867] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:37:38,167] - ThreadPool::destroy(): waiting for thread(2)[0x6dae08,0x6dada0,], try=1
  INFO root [2018-06-28 17:37:41,857] - 
  INFO root [2018-06-28 17:37:41,858] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:37:41,859] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:37:41,859] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:37:41,859] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:37:41,871] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:37:41,871] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:37:41,874] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:17416 )
  INFO root [2018-06-28 17:37:41,875] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:17416, SOMAXCONN=128.
  INFO root [2018-06-28 17:37:41,875] - server-configs:
  INFO root [2018-06-28 17:37:41,875] - 	internalAddr : 192.168.31.56:17416
  INFO root [2018-06-28 17:37:41,875] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:37:41,875] - 	componentID : 9000
  INFO root [2018-06-28 17:37:44,018] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 29051. PID: 3640 ----
  INFO root [2018-06-28 17:37:44,019] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:37:44,020] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:37:44,020] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:37:44,305] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:37:44,307] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:37:44,308] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:37:44,315] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:37:44,316] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:37:44,316] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:37:44,318] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:37:44,417] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:37:44,511] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:37:44,512] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:37:44,517] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:37:44,518] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:37:45,797] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:37:45,797] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 17:37:52,938] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 17:37:53,043] - Components::findComponents: found logger, addr:192.168.31.56:17425
  INFO root [2018-06-28 17:37:53,043] - Components::addComponent: reset orderLog, uid=29051!
  INFO root [2018-06-28 17:37:53,043] - Components::addComponent[logger], uid=29051, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:37:53,046] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 17:37:53,147] - Components::findComponents: found dbmgr, addr:192.168.31.56:17420
  INFO root [2018-06-28 17:37:53,147] - Components::addComponent: reset orderLog, uid=29051!
  INFO root [2018-06-28 17:37:53,147] - Components::addComponent[dbmgr], uid=29051, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:37:53,148] - Components::findComponents: found dbmgr, addr:192.168.31.56:17420
  WARN root [2018-06-28 17:37:54,148] - Forwarding logs to logger[192.168.31.56:17425/0/0/0]...
 ERROR root [2018-06-28 17:47:07,413] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:47:07,425] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:47:07,426] - ==> [2018-06-28 17:47:07 409] TCPPacketReceiver::processPendingEvents(192.168.31.56:17425): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:47:07,426] - ==> [2018-06-28 17:47:07 414] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 17:47:07,533] - TCPPacketReceiver::processPendingEvents(192.168.31.56:17420): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:47:07,540] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:47:07,562] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:47:07,566] - onLoginAppShutDown()
  INFO root [2018-06-28 17:47:07,566] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:47:07,566] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:47:07,567] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:47:07,567] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:47:07,567] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:47:07,568] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:47:07,568] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:47:07,568] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:47:07,569] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:47:07,569] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:47:07,588] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:47:07,588] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:47:07,888] - ThreadPool::destroy(): waiting for thread(2)[0x64ae08,0x64ada0,], try=1
  INFO root [2018-06-28 17:47:35,253] - 
  INFO root [2018-06-28 17:47:35,255] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:47:35,257] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:47:35,258] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:47:35,258] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:47:35,272] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:47:35,273] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:47:35,278] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:17815 )
  INFO root [2018-06-28 17:47:35,278] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:17815, SOMAXCONN=128.
  INFO root [2018-06-28 17:47:35,278] - server-configs:
  INFO root [2018-06-28 17:47:35,279] - 	internalAddr : 192.168.31.56:17815
  INFO root [2018-06-28 17:47:35,279] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:47:35,279] - 	componentID : 9000
  INFO root [2018-06-28 17:47:36,371] - Components::findLogger: found logger, addr:192.168.31.56:17814
  INFO root [2018-06-28 17:47:36,372] - Components::addComponent: reset orderLog, uid=30991!
  INFO root [2018-06-28 17:47:36,372] - Components::addComponent[logger], uid=30991, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:47:36,382] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30991. PID: 9536 ----
  INFO root [2018-06-28 17:47:36,383] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:47:36,383] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:47:36,384] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:47:36,540] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:47:36,542] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:47:36,543] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:47:36,549] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:47:36,549] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:47:36,550] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:47:36,551] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:47:36,628] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:47:36,709] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:47:36,709] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:47:36,713] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:47:36,714] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:47:37,943] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:47:37,945] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 17:47:44,342] - 
  INFO root [2018-06-28 17:47:44,343] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:47:44,345] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:47:44,346] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:47:44,347] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:47:44,372] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:47:44,372] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:47:44,377] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:17839 )
  INFO root [2018-06-28 17:47:44,378] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:17839, SOMAXCONN=128.
  INFO root [2018-06-28 17:47:44,378] - server-configs:
  INFO root [2018-06-28 17:47:44,379] - 	internalAddr : 192.168.31.56:17839
  INFO root [2018-06-28 17:47:44,379] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:47:44,379] - 	componentID : 9000
  INFO root [2018-06-28 17:47:45,921] - Components::findLogger: found logger, addr:192.168.31.56:17833
  INFO root [2018-06-28 17:47:45,922] - Components::addComponent: reset orderLog, uid=31021!
  INFO root [2018-06-28 17:47:45,923] - Components::addComponent[logger], uid=31021, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:47:45,942] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 31021. PID: 9096 ----
  INFO root [2018-06-28 17:47:45,943] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:47:45,958] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:47:45,959] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:47:46,299] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:47:46,301] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:47:46,303] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:47:46,337] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:47:46,339] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:47:46,339] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:47:46,341] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:47:46,559] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:47:46,766] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:47:46,766] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:47:46,772] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:47:46,774] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:47:48,385] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:47:48,392] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 17:47:54,581] - Forwarding logs to logger[192.168.31.56:17833/0/0/0]...
 ERROR root [2018-06-28 17:52:50,335] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:52:50,349] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:52:50,350] - ==> [2018-06-28 17:52:50 330] TCPPacketReceiver::processPendingEvents(192.168.31.56:17833): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:52:50,350] - ==> [2018-06-28 17:52:50 336] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 17:52:50,462] - TCPPacketReceiver::processPendingEvents(192.168.31.56:17834): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:52:50,466] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:52:50,474] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:52:50,487] - onLoginAppShutDown()
  INFO root [2018-06-28 17:52:50,487] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:52:50,487] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:52:50,488] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:52:50,488] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:52:50,488] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:52:50,489] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:52:50,489] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:52:50,489] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:52:50,490] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:52:50,490] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:52:50,508] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:52:50,508] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:52:50,809] - ThreadPool::destroy(): waiting for thread(2)[0x16cae08,0x16cada0,], try=1
  INFO root [2018-06-28 17:52:57,539] - 
  INFO root [2018-06-28 17:52:57,540] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 17:52:57,542] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 17:52:57,543] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 17:52:57,544] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 17:52:57,572] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 17:52:57,572] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 17:52:57,578] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:18072 )
  INFO root [2018-06-28 17:52:57,579] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:18072, SOMAXCONN=128.
  INFO root [2018-06-28 17:52:57,579] - server-configs:
  INFO root [2018-06-28 17:52:57,579] - 	internalAddr : 192.168.31.56:18072
  INFO root [2018-06-28 17:52:57,579] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 17:52:57,580] - 	componentID : 9000
  INFO root [2018-06-28 17:52:59,808] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 32043. PID: 8316 ----
  INFO root [2018-06-28 17:52:59,810] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 17:52:59,810] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 17:52:59,811] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 17:53:00,089] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:53:00,091] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:53:00,093] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:53:00,101] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:53:00,102] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:53:00,103] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:53:00,105] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:53:00,244] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:53:00,344] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 17:53:00,344] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 17:53:00,351] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 17:53:00,352] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 17:53:01,477] - ---- loginapp is running ----
 DEBUG root [2018-06-28 17:53:01,478] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 17:53:08,631] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 17:53:08,697] - Components::findComponents: found logger, addr:192.168.31.56:18066
  INFO root [2018-06-28 17:53:08,697] - Components::addComponent: reset orderLog, uid=32043!
  INFO root [2018-06-28 17:53:08,698] - Components::addComponent[logger], uid=32043, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:53:08,701] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 17:53:08,802] - Components::findComponents: found dbmgr, addr:192.168.31.56:18067
  INFO root [2018-06-28 17:53:08,803] - Components::addComponent: reset orderLog, uid=32043!
  INFO root [2018-06-28 17:53:08,803] - Components::addComponent[dbmgr], uid=32043, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 17:53:08,804] - Components::findComponents: found dbmgr, addr:192.168.31.56:18067
  WARN root [2018-06-28 17:53:09,805] - Forwarding logs to logger[192.168.31.56:18066/0/0/0]...
 ERROR root [2018-06-28 17:53:31,348] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:53:31,370] - The following logs sent to logger failed:
  WARN root [2018-06-28 17:53:31,371] - ==> [2018-06-28 17:53:31 344] TCPPacketReceiver::processPendingEvents(192.168.31.56:18066): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:53:31,372] - ==> [2018-06-28 17:53:31 348] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 17:53:31,515] - TCPPacketReceiver::processPendingEvents(192.168.31.56:18067): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 17:53:31,519] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 17:53:31,549] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 17:53:31,557] - onLoginAppShutDown()
  INFO root [2018-06-28 17:53:31,557] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 17:53:31,557] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 17:53:31,558] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 17:53:31,559] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 17:53:31,559] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 17:53:31,559] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 17:53:31,560] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 17:53:31,560] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 17:53:31,560] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 17:53:31,561] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 17:53:31,584] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 17:53:31,585] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 17:53:31,885] - ThreadPool::destroy(): waiting for thread(2)[0x51bdd0,0x51bd68,], try=1
  INFO root [2018-06-28 18:06:04,087] - 
  INFO root [2018-06-28 18:06:04,090] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 18:06:04,092] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 18:06:04,093] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 18:06:04,093] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 18:06:04,111] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 18:06:04,111] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 18:06:04,116] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:18514 )
  INFO root [2018-06-28 18:06:04,117] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:18514, SOMAXCONN=128.
  INFO root [2018-06-28 18:06:04,117] - server-configs:
  INFO root [2018-06-28 18:06:04,117] - 	internalAddr : 192.168.31.56:18514
  INFO root [2018-06-28 18:06:04,117] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 18:06:04,118] - 	componentID : 9000
  INFO root [2018-06-28 18:06:06,234] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1841. PID: 4720 ----
  INFO root [2018-06-28 18:06:06,236] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 18:06:06,236] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 18:06:06,237] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 18:06:06,419] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:06:06,420] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:06:06,421] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:06:06,429] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:06:06,430] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:06:06,431] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:06:06,433] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:06:06,561] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:06:06,660] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 18:06:06,660] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 18:06:06,666] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 18:06:06,668] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 18:06:08,110] - ---- loginapp is running ----
 DEBUG root [2018-06-28 18:06:08,111] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 18:06:18,934] - 
  INFO root [2018-06-28 18:06:18,935] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 18:06:18,937] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 18:06:18,938] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 18:06:18,939] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 18:06:18,953] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 18:06:18,953] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 18:06:18,965] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:18536 )
  INFO root [2018-06-28 18:06:18,966] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:18536, SOMAXCONN=128.
  INFO root [2018-06-28 18:06:18,966] - server-configs:
  INFO root [2018-06-28 18:06:18,966] - 	internalAddr : 192.168.31.56:18536
  INFO root [2018-06-28 18:06:18,967] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 18:06:18,967] - 	componentID : 9000
  INFO root [2018-06-28 18:06:20,150] - Components::findLogger: found logger, addr:192.168.31.56:18533
  INFO root [2018-06-28 18:06:20,151] - Components::addComponent: reset orderLog, uid=1890!
  INFO root [2018-06-28 18:06:20,151] - Components::addComponent[logger], uid=1890, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 18:06:20,164] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1890. PID: 3624 ----
  INFO root [2018-06-28 18:06:20,165] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 18:06:20,166] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 18:06:20,167] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 18:06:20,329] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:06:20,329] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:06:20,330] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:06:20,335] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:06:20,336] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:06:20,336] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:06:20,337] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:06:20,410] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:06:20,492] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 18:06:20,492] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 18:06:20,498] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 18:06:20,499] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 18:06:21,866] - ---- loginapp is running ----
 DEBUG root [2018-06-28 18:06:21,867] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 18:06:25,318] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20535, errorno=10048
  WARN root [2018-06-28 18:06:28,368] - Forwarding logs to logger[192.168.31.56:18533/0/0/0]...
 ERROR root [2018-06-28 18:06:40,566] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 18:06:40,570] - The following logs sent to logger failed:
  WARN root [2018-06-28 18:06:40,570] - ==> [2018-06-28 18:06:40 563] TCPPacketReceiver::processPendingEvents(192.168.31.56:18533): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 18:06:40,571] - ==> [2018-06-28 18:06:40 567] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 18:06:40,683] - TCPPacketReceiver::processPendingEvents(192.168.31.56:18538): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 18:06:40,690] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 18:06:40,692] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 18:06:40,694] - onLoginAppShutDown()
  INFO root [2018-06-28 18:06:40,694] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 18:06:40,695] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 18:06:40,695] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:06:40,695] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:06:40,696] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:06:40,696] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:06:40,696] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:06:40,697] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:06:40,697] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:06:40,697] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:06:40,717] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 18:06:40,717] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 18:06:41,017] - ThreadPool::destroy(): waiting for thread(2)[0x65bdd0,0x65bd68,], try=1
  INFO root [2018-06-28 18:15:29,783] - 
  INFO root [2018-06-28 18:15:29,784] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 18:15:29,788] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 18:15:29,789] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 18:15:29,789] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 18:15:29,829] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 18:15:29,830] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 18:15:29,835] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:18842 )
  INFO root [2018-06-28 18:15:29,835] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:18842, SOMAXCONN=128.
  INFO root [2018-06-28 18:15:29,836] - server-configs:
  INFO root [2018-06-28 18:15:29,836] - 	internalAddr : 192.168.31.56:18842
  INFO root [2018-06-28 18:15:29,836] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 18:15:29,837] - 	componentID : 9000
  INFO root [2018-06-28 18:15:32,120] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3690. PID: 6360 ----
  INFO root [2018-06-28 18:15:32,122] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 18:15:32,122] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 18:15:32,123] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 18:15:32,393] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:15:32,395] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:15:32,396] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:15:32,407] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:15:32,408] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:15:32,408] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:15:32,410] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:15:32,613] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:15:32,967] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 18:15:32,968] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 18:15:33,007] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 18:15:33,009] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 18:15:34,385] - ---- loginapp is running ----
 DEBUG root [2018-06-28 18:15:34,386] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 18:15:41,548] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 18:15:41,636] - Components::findComponents: found logger, addr:192.168.31.56:18847
  INFO root [2018-06-28 18:15:41,637] - Components::addComponent: reset orderLog, uid=3690!
  INFO root [2018-06-28 18:15:41,638] - Components::addComponent[logger], uid=3690, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 18:15:41,643] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 18:15:41,747] - Components::findComponents: found dbmgr, addr:192.168.31.56:18844
  INFO root [2018-06-28 18:15:41,747] - Components::addComponent: reset orderLog, uid=3690!
  INFO root [2018-06-28 18:15:41,747] - Components::addComponent[dbmgr], uid=3690, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 18:15:41,749] - Components::findComponents: found dbmgr, addr:192.168.31.56:18844
  WARN root [2018-06-28 18:15:42,749] - Forwarding logs to logger[192.168.31.56:18847/0/0/0]...
 ERROR root [2018-06-28 18:29:24,396] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 18:29:24,417] - The following logs sent to logger failed:
  WARN root [2018-06-28 18:29:24,418] - ==> [2018-06-28 18:29:24 393] TCPPacketReceiver::processPendingEvents(192.168.31.56:18847): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 18:29:24,419] - ==> [2018-06-28 18:29:24 399] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 18:29:24,540] - TCPPacketReceiver::processPendingEvents(192.168.31.56:18844): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 18:29:24,552] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 18:29:24,559] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 18:29:24,570] - onLoginAppShutDown()
  INFO root [2018-06-28 18:29:24,570] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 18:29:24,571] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 18:29:24,572] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:29:24,572] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:29:24,572] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:29:24,573] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:29:24,573] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:29:24,573] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:29:24,573] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:29:24,574] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:29:24,595] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 18:29:24,595] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 18:29:24,895] - ThreadPool::destroy(): waiting for thread(2)[0x170bdd0,0x170bd68,], try=1
  INFO root [2018-06-28 18:29:33,621] - 
  INFO root [2018-06-28 18:29:33,643] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 18:29:33,644] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 18:29:33,645] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 18:29:33,645] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 18:29:33,660] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 18:29:33,661] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 18:29:33,664] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:19332 )
  INFO root [2018-06-28 18:29:33,664] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:19332, SOMAXCONN=128.
  INFO root [2018-06-28 18:29:33,664] - server-configs:
  INFO root [2018-06-28 18:29:33,664] - 	internalAddr : 192.168.31.56:19332
  INFO root [2018-06-28 18:29:33,665] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 18:29:33,665] - 	componentID : 9000
  INFO root [2018-06-28 18:29:35,935] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 6446. PID: 4584 ----
  INFO root [2018-06-28 18:29:35,937] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 18:29:35,937] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 18:29:35,938] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 18:29:36,177] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:29:36,179] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:29:36,180] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:29:36,189] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:29:36,190] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:29:36,190] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:29:36,192] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:29:36,357] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:29:36,461] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 18:29:36,462] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 18:29:36,468] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 18:29:36,470] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 18:29:38,149] - ---- loginapp is running ----
 DEBUG root [2018-06-28 18:29:38,150] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 18:29:45,369] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 18:29:45,401] - Components::findComponents: found logger, addr:192.168.31.56:19337
  INFO root [2018-06-28 18:29:45,401] - Components::addComponent: reset orderLog, uid=6446!
  INFO root [2018-06-28 18:29:45,402] - Components::addComponent[logger], uid=6446, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 18:29:45,404] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 18:29:45,505] - Components::findComponents: found dbmgr, addr:192.168.31.56:19339
  INFO root [2018-06-28 18:29:45,505] - Components::addComponent: reset orderLog, uid=6446!
  INFO root [2018-06-28 18:29:45,506] - Components::addComponent[dbmgr], uid=6446, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 18:29:45,506] - Components::findComponents: found dbmgr, addr:192.168.31.56:19339
  WARN root [2018-06-28 18:29:46,506] - Forwarding logs to logger[192.168.31.56:19337/0/0/0]...
 ERROR root [2018-06-28 18:35:40,615] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 18:35:40,628] - The following logs sent to logger failed:
  WARN root [2018-06-28 18:35:40,629] - ==> [2018-06-28 18:35:40 615] TCPPacketReceiver::processPendingEvents(192.168.31.56:19337): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 18:35:40,630] - ==> [2018-06-28 18:35:40 616] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 18:35:40,782] - TCPPacketReceiver::processPendingEvents(192.168.31.56:19339): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 18:35:40,785] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 18:35:40,792] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 18:35:40,793] - onLoginAppShutDown()
  INFO root [2018-06-28 18:35:40,794] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 18:35:40,794] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 18:35:40,795] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 18:35:40,795] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 18:35:40,795] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 18:35:40,795] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 18:35:40,796] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 18:35:40,796] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 18:35:40,796] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 18:35:40,797] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 18:35:40,825] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 18:35:40,826] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 18:35:41,126] - ThreadPool::destroy(): waiting for thread(2)[0x31bdd0,0x31bd68,], try=1
  INFO root [2018-06-28 20:08:37,753] - 
  INFO root [2018-06-28 20:08:37,754] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 20:08:37,755] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 20:08:37,755] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 20:08:37,756] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 20:08:37,765] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 20:08:37,765] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 20:08:37,769] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:21067 )
  INFO root [2018-06-28 20:08:37,769] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:21067, SOMAXCONN=128.
  INFO root [2018-06-28 20:08:37,769] - server-configs:
  INFO root [2018-06-28 20:08:37,769] - 	internalAddr : 192.168.31.56:21067
  INFO root [2018-06-28 20:08:37,769] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 20:08:37,769] - 	componentID : 9000
  INFO root [2018-06-28 20:08:39,872] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 25856. PID: 11148 ----
  INFO root [2018-06-28 20:08:39,875] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 20:08:39,875] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 20:08:39,876] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 20:08:40,110] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 20:08:40,112] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 20:08:40,112] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 20:08:40,121] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 20:08:40,122] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 20:08:40,123] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 20:08:40,124] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 20:08:40,293] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 20:08:40,535] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 20:08:40,537] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 20:08:40,543] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 20:08:40,544] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 20:08:42,103] - ---- loginapp is running ----
 DEBUG root [2018-06-28 20:08:42,104] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 20:08:49,244] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 20:08:49,340] - Components::findComponents: found logger, addr:192.168.31.56:21072
  INFO root [2018-06-28 20:08:49,340] - Components::addComponent: reset orderLog, uid=25856!
  INFO root [2018-06-28 20:08:49,340] - Components::addComponent[logger], uid=25856, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 20:08:49,342] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 20:08:49,444] - Components::findComponents: found dbmgr, addr:192.168.31.56:21074
  INFO root [2018-06-28 20:08:49,444] - Components::addComponent: reset orderLog, uid=25856!
  INFO root [2018-06-28 20:08:49,445] - Components::addComponent[dbmgr], uid=25856, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 20:08:49,446] - Components::findComponents: found dbmgr, addr:192.168.31.56:21074
  WARN root [2018-06-28 20:08:50,446] - Forwarding logs to logger[192.168.31.56:21072/0/0/0]...
 ERROR root [2018-06-28 20:11:37,139] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 20:11:37,156] - The following logs sent to logger failed:
  WARN root [2018-06-28 20:11:37,156] - ==> [2018-06-28 20:11:37 136] TCPPacketReceiver::processPendingEvents(192.168.31.56:21072): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 20:11:37,157] - ==> [2018-06-28 20:11:37 140] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 20:11:37,281] - TCPPacketReceiver::processPendingEvents(192.168.31.56:21074): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 20:11:37,283] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 20:11:37,288] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 20:11:37,294] - onLoginAppShutDown()
  INFO root [2018-06-28 20:11:37,294] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 20:11:37,295] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 20:11:37,295] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 20:11:37,296] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 20:11:37,296] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 20:11:37,296] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 20:11:37,297] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 20:11:37,297] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 20:11:37,297] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 20:11:37,297] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 20:11:37,319] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 20:11:37,319] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 20:11:37,619] - ThreadPool::destroy(): waiting for thread(2)[0x60bdd0,0x60bd68,], try=1
  INFO root [2018-06-28 20:11:43,850] - 
  INFO root [2018-06-28 20:11:43,851] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 20:11:43,853] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 20:11:43,853] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 20:11:43,854] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 20:11:43,889] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 20:11:43,889] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 20:11:43,894] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:21174 )
  INFO root [2018-06-28 20:11:43,894] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:21174, SOMAXCONN=128.
  INFO root [2018-06-28 20:11:43,894] - server-configs:
  INFO root [2018-06-28 20:11:43,895] - 	internalAddr : 192.168.31.56:21174
  INFO root [2018-06-28 20:11:43,895] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 20:11:43,895] - 	componentID : 9000
  INFO root [2018-06-28 20:11:46,038] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 26464. PID: 3484 ----
  INFO root [2018-06-28 20:11:46,041] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 20:11:46,042] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 20:11:46,043] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 20:11:46,285] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 20:11:46,286] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 20:11:46,287] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 20:11:46,296] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 20:11:46,297] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 20:11:46,297] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 20:11:46,299] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 20:11:46,562] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 20:11:46,966] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 20:11:46,966] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 20:11:46,972] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 20:11:46,973] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 20:11:48,352] - ---- loginapp is running ----
 DEBUG root [2018-06-28 20:11:48,353] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 20:11:55,492] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 20:11:55,583] - Components::findComponents: found logger, addr:192.168.31.56:21180
  INFO root [2018-06-28 20:11:55,583] - Components::addComponent: reset orderLog, uid=26464!
  INFO root [2018-06-28 20:11:55,584] - Components::addComponent[logger], uid=26464, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 20:11:55,588] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 20:11:55,692] - Components::findComponents: found dbmgr, addr:192.168.31.56:21182
  INFO root [2018-06-28 20:11:55,692] - Components::addComponent: reset orderLog, uid=26464!
  INFO root [2018-06-28 20:11:55,693] - Components::addComponent[dbmgr], uid=26464, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 20:11:55,694] - Components::findComponents: found dbmgr, addr:192.168.31.56:21182
  WARN root [2018-06-28 20:11:56,694] - Forwarding logs to logger[192.168.31.56:21180/0/0/0]...
 ERROR root [2018-06-28 20:12:58,726] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 20:12:58,771] - The following logs sent to logger failed:
  WARN root [2018-06-28 20:12:58,772] - ==> [2018-06-28 20:12:58 720] TCPPacketReceiver::processPendingEvents(192.168.31.56:21180): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 20:12:58,773] - ==> [2018-06-28 20:12:58 727] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 20:12:58,907] - TCPPacketReceiver::processPendingEvents(192.168.31.56:21182): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 20:12:58,911] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 20:12:58,983] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 20:12:58,985] - onLoginAppShutDown()
  INFO root [2018-06-28 20:12:58,986] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 20:12:58,986] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 20:12:58,987] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 20:12:58,987] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 20:12:58,987] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 20:12:58,988] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 20:12:58,988] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 20:12:58,989] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 20:12:58,989] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 20:12:58,990] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 20:12:59,010] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 20:12:59,010] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 20:12:59,313] - ThreadPool::destroy(): waiting for thread(2)[0x35bdd0,0x35bd68,], try=1
  INFO root [2018-06-28 21:26:59,588] - 
  INFO root [2018-06-28 21:26:59,589] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 21:26:59,590] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 21:26:59,590] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 21:26:59,590] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 21:26:59,601] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 21:26:59,601] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 21:26:59,604] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:22409 )
  INFO root [2018-06-28 21:26:59,604] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:22409, SOMAXCONN=128.
  INFO root [2018-06-28 21:26:59,605] - server-configs:
  INFO root [2018-06-28 21:26:59,605] - 	internalAddr : 192.168.31.56:22409
  INFO root [2018-06-28 21:26:59,605] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 21:26:59,605] - 	componentID : 9000
  INFO root [2018-06-28 21:27:01,895] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 8443. PID: 12148 ----
  INFO root [2018-06-28 21:27:01,896] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 21:27:01,897] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 21:27:01,897] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 21:27:02,074] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 21:27:02,108] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 21:27:02,109] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 21:27:02,119] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 21:27:02,120] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 21:27:02,120] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 21:27:02,122] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 21:27:02,243] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 21:27:02,343] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 21:27:02,344] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 21:27:02,349] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 21:27:02,351] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 21:27:04,086] - ---- loginapp is running ----
 DEBUG root [2018-06-28 21:27:04,088] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 21:27:11,330] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 21:27:11,347] - Components::findComponents: found logger, addr:192.168.31.56:22416
  INFO root [2018-06-28 21:27:11,347] - Components::addComponent: reset orderLog, uid=8443!
  INFO root [2018-06-28 21:27:11,347] - Components::addComponent[logger], uid=8443, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 21:27:11,350] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 21:27:11,353] - Components::findComponents: found logger, addr:192.168.31.56:22416
  INFO root [2018-06-28 21:27:11,457] - Components::findComponents: found dbmgr, addr:192.168.31.56:22414
  INFO root [2018-06-28 21:27:11,457] - Components::addComponent: reset orderLog, uid=8443!
  INFO root [2018-06-28 21:27:11,457] - Components::addComponent[dbmgr], uid=8443, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 21:27:11,458] - Components::findComponents: found dbmgr, addr:192.168.31.56:22414
  WARN root [2018-06-28 21:27:12,458] - Forwarding logs to logger[192.168.31.56:22416/0/0/0]...
 ERROR root [2018-06-28 21:44:49,371] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 21:44:49,382] - The following logs sent to logger failed:
  WARN root [2018-06-28 21:44:49,382] - ==> [2018-06-28 21:44:49 368] TCPPacketReceiver::processPendingEvents(192.168.31.56:22416): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 21:44:49,383] - ==> [2018-06-28 21:44:49 372] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 21:44:49,501] - TCPPacketReceiver::processPendingEvents(192.168.31.56:22414): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 21:44:49,506] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 21:44:49,520] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 21:44:49,528] - onLoginAppShutDown()
  INFO root [2018-06-28 21:44:49,528] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 21:44:49,529] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 21:44:49,530] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 21:44:49,530] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 21:44:49,530] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 21:44:49,530] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 21:44:49,531] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 21:44:49,531] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 21:44:49,531] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 21:44:49,532] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 21:44:49,550] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 21:44:49,551] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 21:44:49,851] - ThreadPool::destroy(): waiting for thread(2)[0x3abdf0,0x3abd88,], try=1
  INFO root [2018-06-28 21:44:54,735] - 
  INFO root [2018-06-28 21:44:54,736] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 21:44:54,737] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 21:44:54,738] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 21:44:54,738] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 21:44:54,751] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 21:44:54,751] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 21:44:54,755] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:22838 )
  INFO root [2018-06-28 21:44:54,756] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:22838, SOMAXCONN=128.
  INFO root [2018-06-28 21:44:54,756] - server-configs:
  INFO root [2018-06-28 21:44:54,756] - 	internalAddr : 192.168.31.56:22838
  INFO root [2018-06-28 21:44:54,756] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 21:44:54,756] - 	componentID : 9000
  INFO root [2018-06-28 21:44:56,920] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 11954. PID: 11760 ----
  INFO root [2018-06-28 21:44:56,921] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 21:44:56,922] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 21:44:56,923] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 21:44:57,139] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 21:44:57,141] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 21:44:57,142] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 21:44:57,150] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 21:44:57,151] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 21:44:57,151] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 21:44:57,153] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 21:44:57,322] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 21:44:57,417] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 21:44:57,418] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 21:44:57,424] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 21:44:57,425] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 21:44:59,287] - ---- loginapp is running ----
 DEBUG root [2018-06-28 21:44:59,293] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 21:45:00,105] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20498, errorno=10048
  INFO root [2018-06-28 21:45:07,323] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 21:45:07,348] - Components::findComponents: found logger, addr:192.168.31.56:22843
  INFO root [2018-06-28 21:45:07,349] - Components::addComponent: reset orderLog, uid=11954!
  INFO root [2018-06-28 21:45:07,349] - Components::addComponent[logger], uid=11954, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 21:45:07,351] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 21:45:07,355] - Components::findComponents: found logger, addr:192.168.31.56:22843
  INFO root [2018-06-28 21:45:07,460] - Components::findComponents: found dbmgr, addr:192.168.31.56:22844
  INFO root [2018-06-28 21:45:07,461] - Components::addComponent: reset orderLog, uid=11954!
  INFO root [2018-06-28 21:45:07,461] - Components::addComponent[dbmgr], uid=11954, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 21:45:07,462] - Components::findComponents: found dbmgr, addr:192.168.31.56:22844
  WARN root [2018-06-28 21:45:08,462] - Forwarding logs to logger[192.168.31.56:22843/0/0/0]...
 ERROR root [2018-06-28 21:46:33,556] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 21:46:33,571] - The following logs sent to logger failed:
  WARN root [2018-06-28 21:46:33,572] - ==> [2018-06-28 21:46:33 549] TCPPacketReceiver::processPendingEvents(192.168.31.56:22843): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 21:46:33,572] - ==> [2018-06-28 21:46:33 558] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 21:46:33,685] - TCPPacketReceiver::processPendingEvents(192.168.31.56:22844): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 21:46:33,690] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 21:46:33,698] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 21:46:33,713] - onLoginAppShutDown()
  INFO root [2018-06-28 21:46:33,713] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 21:46:33,714] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 21:46:33,714] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 21:46:33,714] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 21:46:33,715] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 21:46:33,715] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 21:46:33,715] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 21:46:33,716] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 21:46:33,716] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 21:46:33,716] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 21:46:33,733] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 21:46:33,733] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 21:46:34,033] - ThreadPool::destroy(): waiting for thread(2)[0x62ae08,0x62ada0,], try=1
  INFO root [2018-06-28 21:46:38,774] - 
  INFO root [2018-06-28 21:46:38,775] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 21:46:38,777] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 21:46:38,778] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 21:46:38,778] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 21:46:38,792] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 21:46:38,792] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 21:46:38,798] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:22935 )
  INFO root [2018-06-28 21:46:38,799] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:22935, SOMAXCONN=128.
  INFO root [2018-06-28 21:46:38,799] - server-configs:
  INFO root [2018-06-28 21:46:38,799] - 	internalAddr : 192.168.31.56:22935
  INFO root [2018-06-28 21:46:38,800] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 21:46:38,800] - 	componentID : 9000
  INFO root [2018-06-28 21:46:39,251] - Components::findLogger: found logger, addr:192.168.31.56:22930
  INFO root [2018-06-28 21:46:39,252] - Components::addComponent: reset orderLog, uid=12290!
  INFO root [2018-06-28 21:46:39,252] - Components::addComponent[logger], uid=12290, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 21:46:39,272] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 12290. PID: 8224 ----
  INFO root [2018-06-28 21:46:39,273] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 21:46:39,274] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 21:46:39,275] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 21:46:39,428] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 21:46:39,429] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 21:46:39,429] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 21:46:39,435] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 21:46:39,435] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 21:46:39,436] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 21:46:39,437] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 21:46:39,515] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 21:46:39,590] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 21:46:39,591] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 21:46:39,596] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 21:46:39,597] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 21:46:40,645] - ---- loginapp is running ----
 DEBUG root [2018-06-28 21:46:40,646] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 21:46:47,023] - Forwarding logs to logger[192.168.31.56:22930/0/0/0]...
 ERROR root [2018-06-28 22:19:31,007] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 22:19:31,022] - The following logs sent to logger failed:
  WARN root [2018-06-28 22:19:31,022] - ==> [2018-06-28 22:19:31 004] TCPPacketReceiver::processPendingEvents(192.168.31.56:22930): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 22:19:31,023] - ==> [2018-06-28 22:19:31 008] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 22:19:31,160] - TCPPacketReceiver::processPendingEvents(192.168.31.56:22933): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 22:19:31,164] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 22:19:31,166] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 22:19:31,167] - onLoginAppShutDown()
  INFO root [2018-06-28 22:19:31,167] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 22:19:31,168] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 22:19:31,169] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 22:19:31,169] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 22:19:31,169] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 22:19:31,170] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 22:19:31,171] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 22:19:31,172] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 22:19:31,172] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 22:19:31,173] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 22:19:31,194] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 22:19:31,194] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 22:19:31,494] - ThreadPool::destroy(): waiting for thread(2)[0x3bae08,0x3bada0,], try=1
  INFO root [2018-06-28 22:19:35,159] - 
  INFO root [2018-06-28 22:19:35,160] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 22:19:35,162] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 22:19:35,163] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 22:19:35,164] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 22:19:35,227] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 22:19:35,231] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 22:19:35,236] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:23941 )
  INFO root [2018-06-28 22:19:35,241] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:23941, SOMAXCONN=128.
  INFO root [2018-06-28 22:19:35,241] - server-configs:
  INFO root [2018-06-28 22:19:35,242] - 	internalAddr : 192.168.31.56:23941
  INFO root [2018-06-28 22:19:35,242] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 22:19:35,243] - 	componentID : 9000
  INFO root [2018-06-28 22:19:36,867] - Components::findLogger: found logger, addr:192.168.31.56:23938
  INFO root [2018-06-28 22:19:36,868] - Components::addComponent: reset orderLog, uid=18746!
  INFO root [2018-06-28 22:19:36,868] - Components::addComponent[logger], uid=18746, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 22:19:36,884] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 18746. PID: 4456 ----
  INFO root [2018-06-28 22:19:36,894] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 22:19:36,895] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 22:19:36,896] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 22:19:37,176] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 22:19:37,178] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 22:19:37,179] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 22:19:37,189] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 22:19:37,190] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 22:19:37,190] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 22:19:37,192] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 22:19:37,557] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 22:19:37,718] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 22:19:37,718] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 22:19:37,725] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 22:19:37,726] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 22:19:39,621] - ---- loginapp is running ----
 DEBUG root [2018-06-28 22:19:39,622] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 22:19:45,798] - Forwarding logs to logger[192.168.31.56:23938/0/0/0]...
 ERROR root [2018-06-28 22:26:25,395] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 22:26:25,404] - The following logs sent to logger failed:
  WARN root [2018-06-28 22:26:25,405] - ==> [2018-06-28 22:26:25 388] TCPPacketReceiver::processPendingEvents(192.168.31.56:23938): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 22:26:25,405] - ==> [2018-06-28 22:26:25 396] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 22:26:25,518] - TCPPacketReceiver::processPendingEvents(192.168.31.56:23944): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 22:26:25,524] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 22:26:25,531] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 22:26:25,533] - onLoginAppShutDown()
  INFO root [2018-06-28 22:26:25,533] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 22:26:25,533] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 22:26:25,534] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 22:26:25,535] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 22:26:25,535] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 22:26:25,535] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 22:26:25,536] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 22:26:25,536] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 22:26:25,537] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 22:26:25,537] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 22:26:25,556] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 22:26:25,556] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 22:26:25,856] - ThreadPool::destroy(): waiting for thread(2)[0x4cae08,0x4cada0,], try=1
  INFO root [2018-06-28 22:27:23,813] - 
  INFO root [2018-06-28 22:27:23,815] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 22:27:23,817] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 22:27:23,818] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 22:27:23,819] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 22:27:23,832] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 22:27:23,832] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 22:27:23,837] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:24215 )
  INFO root [2018-06-28 22:27:23,837] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:24215, SOMAXCONN=128.
  INFO root [2018-06-28 22:27:23,837] - server-configs:
  INFO root [2018-06-28 22:27:23,838] - 	internalAddr : 192.168.31.56:24215
  INFO root [2018-06-28 22:27:23,838] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 22:27:23,838] - 	componentID : 9000
  INFO root [2018-06-28 22:27:24,875] - Components::findLogger: found logger, addr:192.168.31.56:24208
  INFO root [2018-06-28 22:27:24,876] - Components::addComponent: reset orderLog, uid=20274!
  INFO root [2018-06-28 22:27:24,876] - Components::addComponent[logger], uid=20274, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 22:27:24,884] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 20274. PID: 7160 ----
  INFO root [2018-06-28 22:27:24,884] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 22:27:24,885] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 22:27:24,885] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 22:27:25,040] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 22:27:25,041] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 22:27:25,042] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 22:27:25,048] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 22:27:25,049] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 22:27:25,050] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 22:27:25,051] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 22:27:25,114] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 22:27:25,177] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 22:27:25,177] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 22:27:25,181] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 22:27:25,182] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 22:27:26,994] - ---- loginapp is running ----
 DEBUG root [2018-06-28 22:27:26,997] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 22:27:33,310] - Forwarding logs to logger[192.168.31.56:24208/0/0/0]...
 ERROR root [2018-06-28 22:30:51,438] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 22:30:51,458] - The following logs sent to logger failed:
  WARN root [2018-06-28 22:30:51,458] - ==> [2018-06-28 22:30:51 438] TCPPacketReceiver::processPendingEvents(192.168.31.56:24208): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 22:30:51,458] - ==> [2018-06-28 22:30:51 448] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 22:30:51,588] - TCPPacketReceiver::processPendingEvents(192.168.31.56:24210): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 22:30:51,588] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 22:30:51,598] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 22:30:51,598] - onLoginAppShutDown()
  INFO root [2018-06-28 22:30:51,598] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 22:30:51,598] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 22:30:51,598] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 22:30:51,618] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 22:30:51,618] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 22:30:51,918] - ThreadPool::destroy(): waiting for thread(2)[0x39ae08,0x39ada0,], try=1
  INFO root [2018-06-28 23:30:10,149] - 
  INFO root [2018-06-28 23:30:10,150] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 23:30:10,151] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 23:30:10,151] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 23:30:10,152] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 23:30:10,161] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 23:30:10,161] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 23:30:10,164] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:26352 )
  INFO root [2018-06-28 23:30:10,164] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:26352, SOMAXCONN=128.
  INFO root [2018-06-28 23:30:10,164] - server-configs:
  INFO root [2018-06-28 23:30:10,164] - 	internalAddr : 192.168.31.56:26352
  INFO root [2018-06-28 23:30:10,164] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 23:30:10,164] - 	componentID : 9000
  INFO root [2018-06-28 23:30:12,080] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 32579. PID: 3284 ----
  INFO root [2018-06-28 23:30:12,081] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 23:30:12,081] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 23:30:12,082] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 23:30:12,229] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:30:12,230] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:30:12,231] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:30:12,237] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:30:12,237] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:30:12,238] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:30:12,238] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:30:12,302] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:30:12,376] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 23:30:12,376] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 23:30:12,381] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 23:30:12,382] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 23:30:13,763] - ---- loginapp is running ----
 DEBUG root [2018-06-28 23:30:13,766] - Components::process(): Request for the process of identity...
  INFO root [2018-06-28 23:30:20,980] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 23:30:20,999] - Components::findComponents: found logger, addr:192.168.31.56:26360
  INFO root [2018-06-28 23:30:20,999] - Components::addComponent: reset orderLog, uid=32579!
  INFO root [2018-06-28 23:30:21,000] - Components::addComponent[logger], uid=32579, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:30:21,004] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 23:30:21,105] - Components::findComponents: found dbmgr, addr:192.168.31.56:26358
  INFO root [2018-06-28 23:30:21,106] - Components::addComponent: reset orderLog, uid=32579!
  INFO root [2018-06-28 23:30:21,106] - Components::addComponent[dbmgr], uid=32579, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:30:21,107] - Components::findComponents: found dbmgr, addr:192.168.31.56:26358
  WARN root [2018-06-28 23:30:22,108] - Forwarding logs to logger[192.168.31.56:26360/0/0/0]...
  INFO root [2018-06-28 23:30:37,039] - 
  INFO root [2018-06-28 23:30:37,041] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 23:30:37,043] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 23:30:37,043] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 23:30:37,044] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 23:30:37,057] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 23:30:37,058] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 23:30:37,085] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:26411 )
  INFO root [2018-06-28 23:30:37,085] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:26411, SOMAXCONN=128.
  INFO root [2018-06-28 23:30:37,086] - server-configs:
  INFO root [2018-06-28 23:30:37,086] - 	internalAddr : 192.168.31.56:26411
  INFO root [2018-06-28 23:30:37,086] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 23:30:37,087] - 	componentID : 9000
  INFO root [2018-06-28 23:30:37,948] - Components::findLogger: found logger, addr:192.168.31.56:26405
  INFO root [2018-06-28 23:30:37,949] - Components::addComponent: reset orderLog, uid=32664!
  INFO root [2018-06-28 23:30:37,949] - Components::addComponent[logger], uid=32664, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:30:37,962] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 32664. PID: 5584 ----
  INFO root [2018-06-28 23:30:37,962] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 23:30:37,964] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 23:30:37,965] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 23:30:38,145] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:30:38,147] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:30:38,150] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:30:38,160] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:30:38,161] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:30:38,162] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:30:38,164] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:30:38,349] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:30:38,611] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 23:30:38,612] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 23:30:38,619] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 23:30:38,620] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 23:30:40,159] - ---- loginapp is running ----
 DEBUG root [2018-06-28 23:30:40,172] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 23:30:46,545] - Forwarding logs to logger[192.168.31.56:26405/0/0/0]...
 ERROR root [2018-06-28 23:32:38,329] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:32:38,340] - The following logs sent to logger failed:
  WARN root [2018-06-28 23:32:38,341] - ==> [2018-06-28 23:32:38 326] TCPPacketReceiver::processPendingEvents(192.168.31.56:26405): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:32:38,342] - ==> [2018-06-28 23:32:38 330] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 23:32:38,457] - TCPPacketReceiver::processPendingEvents(192.168.31.56:26410): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:32:38,467] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:32:38,481] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 23:32:38,482] - onLoginAppShutDown()
  INFO root [2018-06-28 23:32:38,483] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 23:32:38,483] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 23:32:38,484] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:32:38,484] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:32:38,484] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:32:38,485] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:32:38,485] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:32:38,485] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:32:38,485] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:32:38,486] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:32:38,505] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 23:32:38,506] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 23:32:38,806] - ThreadPool::destroy(): waiting for thread(2)[0x182ae08,0x182ada0,], try=1
  INFO root [2018-06-28 23:32:45,311] - 
  INFO root [2018-06-28 23:32:45,312] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 23:32:45,314] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 23:32:45,314] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 23:32:45,315] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 23:32:45,412] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 23:32:45,412] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 23:32:45,471] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:26522 )
  INFO root [2018-06-28 23:32:45,472] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:26522, SOMAXCONN=128.
  INFO root [2018-06-28 23:32:45,473] - server-configs:
  INFO root [2018-06-28 23:32:45,473] - 	internalAddr : 192.168.31.56:26522
  INFO root [2018-06-28 23:32:45,473] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 23:32:45,473] - 	componentID : 9000
  INFO root [2018-06-28 23:32:46,683] - Components::findLogger: found logger, addr:192.168.31.56:26517
  INFO root [2018-06-28 23:32:46,684] - Components::addComponent: reset orderLog, uid=314!
  INFO root [2018-06-28 23:32:46,684] - Components::addComponent[logger], uid=314, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:32:46,695] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 314. PID: 11720 ----
  INFO root [2018-06-28 23:32:46,695] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 23:32:46,696] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 23:32:46,697] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 23:32:46,886] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:32:46,888] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:32:46,889] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:32:46,901] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:32:46,902] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:32:46,902] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:32:46,904] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:32:47,016] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:32:47,133] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 23:32:47,134] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 23:32:47,139] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 23:32:47,141] - TelnetServer server is running on port 31000
  WARN root [2018-06-28 23:32:47,585] - c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\server\loginapp\loginapp.cpp:171: Profile scriptCall took 0.45 seconds
  INFO root [2018-06-28 23:32:48,858] - ---- loginapp is running ----
 DEBUG root [2018-06-28 23:32:48,860] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 23:32:52,320] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20302, errorno=10048
  WARN root [2018-06-28 23:32:52,642] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20373, errorno=10048
  WARN root [2018-06-28 23:32:55,687] - Forwarding logs to logger[192.168.31.56:26517/0/0/0]...
 ERROR root [2018-06-28 23:36:56,262] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:36:56,275] - The following logs sent to logger failed:
  WARN root [2018-06-28 23:36:56,276] - ==> [2018-06-28 23:36:56 259] TCPPacketReceiver::processPendingEvents(192.168.31.56:26517): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:36:56,277] - ==> [2018-06-28 23:36:56 263] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 23:36:56,385] - TCPPacketReceiver::processPendingEvents(192.168.31.56:26518): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:36:56,388] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:36:56,409] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 23:36:56,410] - onLoginAppShutDown()
  INFO root [2018-06-28 23:36:56,411] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 23:36:56,411] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 23:36:56,412] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:36:56,412] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:36:56,412] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:36:56,412] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:36:56,413] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:36:56,413] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:36:56,413] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:36:56,414] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:36:56,432] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 23:36:56,432] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 23:36:56,732] - ThreadPool::destroy(): waiting for thread(2)[0x42bdf0,0x42bd88,], try=1
  INFO root [2018-06-28 23:37:01,241] - 
  INFO root [2018-06-28 23:37:01,242] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 23:37:01,244] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 23:37:01,245] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 23:37:01,245] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 23:37:01,257] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 23:37:01,258] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 23:37:01,262] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:26709 )
  INFO root [2018-06-28 23:37:01,263] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:26709, SOMAXCONN=128.
  INFO root [2018-06-28 23:37:01,263] - server-configs:
  INFO root [2018-06-28 23:37:01,263] - 	internalAddr : 192.168.31.56:26709
  INFO root [2018-06-28 23:37:01,263] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 23:37:01,263] - 	componentID : 9000
  INFO root [2018-06-28 23:37:03,407] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1150. PID: 12776 ----
  INFO root [2018-06-28 23:37:03,408] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 23:37:03,409] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 23:37:03,410] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 23:37:03,634] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:37:03,636] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:37:03,637] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:37:03,645] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:37:03,645] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:37:03,646] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:37:03,647] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:37:03,842] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:37:04,043] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 23:37:04,044] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 23:37:04,054] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 23:37:04,056] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 23:37:05,633] - ---- loginapp is running ----
 DEBUG root [2018-06-28 23:37:05,667] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 23:37:05,984] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20442, errorno=10048
  INFO root [2018-06-28 23:37:13,235] - Components::findComponents: find logger(1)...
  INFO root [2018-06-28 23:37:13,283] - Components::findComponents: found logger, addr:192.168.31.56:26707
  INFO root [2018-06-28 23:37:13,283] - Components::addComponent: reset orderLog, uid=1150!
  INFO root [2018-06-28 23:37:13,283] - Components::addComponent[logger], uid=1150, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:37:13,285] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-28 23:37:13,387] - Components::findComponents: found dbmgr, addr:192.168.31.56:26702
  INFO root [2018-06-28 23:37:13,387] - Components::addComponent: reset orderLog, uid=1150!
  INFO root [2018-06-28 23:37:13,387] - Components::addComponent[dbmgr], uid=1150, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:37:13,388] - Components::findComponents: found dbmgr, addr:192.168.31.56:26702
  WARN root [2018-06-28 23:37:14,388] - Forwarding logs to logger[192.168.31.56:26707/0/0/0]...
 ERROR root [2018-06-28 23:40:10,258] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:40:10,264] - The following logs sent to logger failed:
  WARN root [2018-06-28 23:40:10,265] - ==> [2018-06-28 23:40:10 256] TCPPacketReceiver::processPendingEvents(192.168.31.56:26707): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:40:10,266] - ==> [2018-06-28 23:40:10 259] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 23:40:10,419] - TCPPacketReceiver::processPendingEvents(192.168.31.56:26702): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:40:10,421] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:40:10,424] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 23:40:10,426] - onLoginAppShutDown()
  INFO root [2018-06-28 23:40:10,427] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 23:40:10,427] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 23:40:10,428] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:40:10,429] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:40:10,429] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:40:10,429] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:40:10,430] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:40:10,430] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:40:10,430] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:40:10,431] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:40:10,449] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 23:40:10,449] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 23:40:10,750] - ThreadPool::destroy(): waiting for thread(2)[0x177bdf0,0x177bd88,], try=1
  INFO root [2018-06-28 23:40:15,520] - 
  INFO root [2018-06-28 23:40:15,520] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-28 23:40:15,522] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-28 23:40:15,523] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-28 23:40:15,523] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-28 23:40:15,534] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-28 23:40:15,534] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-28 23:40:15,538] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:26848 )
  INFO root [2018-06-28 23:40:15,539] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:26848, SOMAXCONN=128.
  INFO root [2018-06-28 23:40:15,539] - server-configs:
  INFO root [2018-06-28 23:40:15,539] - 	internalAddr : 192.168.31.56:26848
  INFO root [2018-06-28 23:40:15,539] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-28 23:40:15,539] - 	componentID : 9000
  INFO root [2018-06-28 23:40:16,654] - Components::findLogger: found logger, addr:192.168.31.56:26845
  INFO root [2018-06-28 23:40:16,654] - Components::addComponent: reset orderLog, uid=1787!
  INFO root [2018-06-28 23:40:16,654] - Components::addComponent[logger], uid=1787, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-28 23:40:16,654] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1787. PID: 13220 ----
  INFO root [2018-06-28 23:40:16,654] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-28 23:40:16,654] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-28 23:40:16,654] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:40:16,654] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:40:17,034] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-28 23:40:17,034] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-28 23:40:17,034] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-28 23:40:17,034] - TelnetServer server is running on port 31000
  INFO root [2018-06-28 23:40:18,913] - ---- loginapp is running ----
 DEBUG root [2018-06-28 23:40:18,913] - Components::process(): Request for the process of identity...
  WARN root [2018-06-28 23:40:25,119] - Forwarding logs to logger[192.168.31.56:26845/0/0/0]...
 ERROR root [2018-06-28 23:50:21,547] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:50:21,547] - The following logs sent to logger failed:
  WARN root [2018-06-28 23:50:21,547] - ==> [2018-06-28 23:50:21 540] TCPPacketReceiver::processPendingEvents(192.168.31.56:26845): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:50:21,547] - ==> [2018-06-28 23:50:21 547] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-28 23:50:21,547] - TCPPacketReceiver::processPendingEvents(192.168.31.56:26847): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-28 23:50:21,547] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-28 23:50:21,547] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-28 23:50:21,547] - onLoginAppShutDown()
  INFO root [2018-06-28 23:50:21,547] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-28 23:50:21,547] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-28 23:50:21,547] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-28 23:50:21,547] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-28 23:50:21,547] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-28 23:50:21,547] - ThreadPool::destroy(): waiting for thread(2)[0x169bdf0,0x169bd88,], try=1
